### ISSUE TITLE
esp_ble_gap_update_whitelist has no parameter for address type?

### ISSUE THREAD

**Issue by Intrpt** [nkolban/esp32-snippets#1056]
Hi guys,

I'm trying to implement a whitelist on my ESP32 device.
The Device which I want to whitelist has a `BLE_ADDR_TYPE_RANDOM`. Therefore the address is changing within every broadcast.
But if my study is correct it should be possible to whitelist the device with his Identity Resolving Key right?

However, my Problem is that I'm adding the device to the whitelist with `BLEDevice::whiteListAdd` but it's still not possible to get access to the device.
I think it might be because of the address type. 
I'm confused because the ESP32 documentation says there is a parameter for "address type" ( https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/bluetooth/esp_gap_ble.html#_CPPv428esp_ble_gap_update_whitelistb13esp_bd_addr_t22esp_ble_wl_addr_type_t ). 

But in the Arduino Code the parameters are only bool `add_remove` and `esp_bd_addr_t remote_bda` , see: https://github.com/nkolban/esp32-snippets/blob/fe3d318acddf87c6918944f24e8b899d63c816dd/cpp_utils/BLEDevice.cpp#L488 

So the one for address type is missing. Therefore if I add my Address to the whitelist the library does not know that this is a random address. Maybe this is why it is not working?

Is there a bug in the library or do I think the wrong way?

**Comment by chegewara** [comment]
It the difference in API between v3.3 and latest (library has been created for v3.3 and didnt update since then):
https://docs.espressif.com/projects/esp-idf/en/v3.3/api-reference/bluetooth/esp_gap_ble.html#_CPPv428esp_ble_gap_update_whitelistb13esp_bd_addr_t
