### ISSUE TITLE
Error when compilling for nodemcu

### ISSUE THREAD

**Issue by chandru912** [nkolban/esp32-snippets#1060]
Arduino: 1.8.5 (Windows 10), Board: "NodeMCU 1.0 (ESP-12E Module), 80 MHz, Flash, Legacy (new can return nullptr), All SSL ciphers (most compatible), 4MB (FS:2MB OTA:~1019KB), 2, v2 Lower Memory, Disabled, None, Only Sketch, 115200"

WARNING: Category 'Communication,AsyncTCP,AsyncHTTP' in library AsyncHTTPRequest_Generic is not valid. Setting to 'Uncategorized'
In file included from C:\Users\Chandru\Documents\Arduino\message_to_server\sketch_mar17a\sketch_mar22a\sketch_mar25a\sketch_mar25a.ino:14:0:

C:\Users\Chandru\Documents\Arduino\libraries\AsyncTCP-master\src/AsyncTCP.h:26:23: fatal error: sdkconfig.h: No such file or directory

 #include "sdkconfig.h"

                       ^

compilation terminated.

exit status 1
Error compiling for board NodeMCU 1.0 (ESP-12E Module).

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by skavengeer** [comment]
Arduino: 2.0.4 (Windows 10), Board: Uno
 #include "sdkconfig.h"
          ^~~~~~~~~~~~~
compilation terminated.

exit status 1

Compilation error: exit status 1
