### ISSUE TITLE
Plz provide me with the exact code

### ISSUE THREAD

**Issue by harsimrat11** [nkolban/esp32-snippets#1063]
I’m new to programming. So plz can you provide me the Full exact code. I can’t even change a line so plz provide me and make sure that it’s compilable
AND IS THE CODE AVAILABLE FOR Esp8266

**Comment by chegewara** [comment]
You dont have to change code and it is compatible with esp8266
```
void setup() {
  // put your setup code here, to run once:

}

void loop() {
  // put your main code here, to run repeatedly:

}
```

**Comment by harsimrat11** [comment]
Bro but where is the code I’m not able to find it
It’s my humble request to send the exact code
Plz don’t share any link

Just spare a min and copy here 🙏🏻🙏🏻
