### ISSUE TITLE
Plz provide me the .ino file🙏🏻

### ISSUE THREAD

**Issue by harsimrat11** [nkolban/esp32-snippets#1064]
I’m using arduino ide to send this program to esp8266 and I’m using 0.96 inch i2c display 

PLZ PROVIDE ME THE .ino file because I’m new to this
IF I CAN GET A TUTORIAL REGARDING THIS THEN IT WOULD ME MUCH BETTER AND APPRECIATED.

**Comment by gromeck** [comment]
The ESP8266 has no bluetooth.
There is no .ino file, but there are examples which you can retrieve in the IDE via File->Examples->ESP ...

Please close this issue.
