### ISSUE TITLE
Alternatives to just serial printing pCharacteristic->getValues?

### ISSUE THREAD

**Issue by darrenjcosborne** [nkolban/esp32-snippets#1079]
I have an ESP32 running the following code, which works perfectly to display pCharacteristic values sent from a client phone app:

````Cpp
class MyCallbacks: public BLECharacteristicCallbacks {
    void onWrite(BLECharacteristic *pCharacteristic) {
      std::string value = pCharacteristic->getValue();

      if (value.length() > 0) {
        Serial.println("*********");
        Serial.print("New value: ");
        for (int i = 0; i < value.length(); i++)
          Serial.print(value[i]);

        Serial.println();
        Serial.println("*********");
      }
    }
};
````

However, I would like to send the BLE server different string values (to control the device within other functions), but I'm at a loss figuring how to parse this information (possibly as a concatenated string) outside of this class? Basically, I would like to do more than just set the pinMode to High or Low, or print to the Serial Monitor. Maybe something like the following:

````Cpp
for (int i = 0; i < rxValue.length(); i++){
      Rx[i] = rxValue[i];
    }
````

At this point, send 'Rx' to another function `doSomething(Rx)` or as per below, utilise further string functions, breaking down the information that has been sent to the server:

````Cpp
if (strstr(Rx, "SET TIMER: ") == &Rx[0]){
      Serial.println("Setting Timer");
      // Code to send Rx to another class (to run further string functions) or alternatively, run a function from another class
    } else if { (strstr(Rx, "START STOPWATCH:") == &Rx[0]){
      // etc
    }
// etc
````

Is it possible for you to create some examples for this type of functionality... (thus helping to improve the usability of this library) please?
Thanks

**Comment by chegewara** [comment]
I am not saying you are doing something wrong, but why waste bytes to send strings?
You can send byte values like this:
- 0x01 - set timer
- 0x02 - set somethings else
- 0x03 - do somethings else

1st byte is command, next bytes can be parse depending on command type. Then use switch/case for example.

**Comment by darrenjcosborne** [comment]
Ok, that's something I hadn't considered. Thanks.
