### ISSUE TITLE
ESP32 BLE pairing 

### ISSUE THREAD

**Issue by ghost** [nkolban/esp32-snippets#1146]

**Comment by benjaminaigner** [comment]
Dear @sonu11-cloud,

sorry, issues don't work this way.
Do you have a problem with this repository?
If yes, describe the problem and people (hopefully) fix it.

Is it an enhancement? Kindly ask if the developers implement it.

>I need a code for this which works in Arduino IDE software.

What did you try so far?
Personally, I'm not an expert on this level of BLE.

And I think this way of request won't help you here, kindly ask and provide your current progress.
Nobody is just implementing this for you, you have to try it on your own. If you are not willing to develop it by yourself, go to upwork.com or any other platform and pay for the implementation.

Greetings & good luck with your project.
