### ISSUE TITLE
WebSocket.cpp Compilation Error

### ISSUE THREAD

**Issue by wiltOS** [nkolban/esp32-snippets#119]
For some reason WebSocket is giving some very strange errors. I have been trying to compile the bootwifi.c file located here: https://github.com/nkolban/esp32-snippets/tree/master/networking/bootwifi

> Z:/projects/hardware-cls/components/cpp_utils/WebSocket.cpp: In member function 'void WebServer::HTTPResponse::sendChunkHead()':
> Z:/projects/hardware-cls/components/cpp_utils/WebSocket.cpp:495:48: error: 'class std::map<std::__cxx11::basic_string<char>, std::__cxx11::basic_string<char> >' has no member named 'c_str'
>      mg_send_head(m_nc, m_status, -1, m_headers.c_str());
>                                                 ^
> Z:/projects/hardware-cls/components/cpp_utils/WebSocket.cpp: At global scope:
> Z:/projects/hardware-cls/components/cpp_utils/WebSocket.cpp:507:6: error: redefinition of 'void WebServer::HTTPResponse::sendData(const char*, size_t)'
>  void WebServer::HTTPResponse::sendData(const char* pData, size_t length) {
>       ^
> Z:/projects/hardware-cls/components/cpp_utils/WebSocket.cpp:486:6: note: 'void WebServer::HTTPResponse::sendData(const char*, size_t)' previously defined here
>  void WebServer::HTTPResponse::sendData(const char* pData, size_t length) {

I have compiled this before without a problem, but ever since we fixed the esp32 libcurl integration I have been getting an error. Here is the entire compilation:

https://pastebin.com/ezg9kVuz

Thank you for the help

**Comment by nkolban** [comment]
I'm going to rebuild bootwifi to use the new HttpServer classes.

**Comment by nkolban** [comment]
Coding 80% complete but now blocked waiting on the new ESP32 v3.0 C++ exception handling which should only be 2-3 weeks out.

**Comment by nkolban** [comment]
The whole of the bootwifi code has been revamped.  It is now C++ based and no longer has Mongoose as a pre-req.  It is now 100% self contained.

**Comment by nkolban** [comment]
Closing for just now.  Re-open as needed.
