### ISSUE TITLE
BLERemoteService Compile Error 

### ISSUE THREAD

**Issue by SamiKNofal** [nkolban/esp32-snippets#128]
Good day!
So I downloaded your ESP32 BLE library but it seems that every time I compile any of the given examples I get the following error for BLERemoteService. Below is an attached picture with the full error report. Can you please tell me why I keep getting this compiling error.
Thanks!

![untitled](https://user-images.githubusercontent.com/32852776/31634878-c3338f8c-b279-11e7-9057-934122a9c53f.png)

**Comment by nkolban** [comment]
Howdy ... I saw you closed it ... did you find a solution?
