### ISSUE TITLE
Build error - do not seem to have socketpair as part of components

### ISSUE THREAD

**Issue by ponnappatallac** [nkolban/esp32-snippets#13]
I followed the instruction on building libcurl (Thank you for the detail steps and video).  However I seem to be getting the following error : 
/home/user/esp/libcurl4/components/curl/lib/curl_ntlm_wb.c: In function 'Curl_ntlm_wb_cleanup':
/home/user/esp/libcurl4/components/curl/lib/curl_ntlm_wb.c:91:9: error: implicit declaration of function 'kill' [-Werror=implicit-function-declaration]
         kill(conn->ntlm_auth_hlpr_pid, SIGTERM);
         ^
/home/user/esp/libcurl4/components/curl/lib/curl_ntlm_wb.c: In function 'ntlm_wb_init':
/home/user/esp/libcurl4/components/curl/lib/curl_ntlm_wb.c:187:6: error: implicit declaration of function 'socketpair' [-Werror=implicit-function-declaration]
   if(socketpair(AF_UNIX, SOCK_STREAM, 0, sockfds)) {
      ^
/home/user/esp/libcurl4/components/curl/lib/curl_ntlm_wb.c:187:17: error: 'AF_UNIX' undeclared (first use in this function)
   if(socketpair(AF_UNIX, SOCK_STREAM, 0, sockfds)) {
                 ^
/home/user/esp/libcurl4/components/curl/lib/curl_ntlm_wb.c:187:17: note: each undeclared identifier is reported only once for each function it appears in

**Comment by mgleason** [comment]
Same here...

**Comment by nkolban** [comment]
Thanks guys.  Sorry for the delay in getting back to y'all.   I have updated the project sample files here and all should now work.  The addition was

```
#define CURL_DISABLE_NTLM 1
```
`into lib/curl_config.h`

Many thanks to @mgleason for spending live time helping me debug this.

@ponnappatallac  Please check that it works for you now and let me know.

**Comment by ponnappatallac** [comment]
Thank you for your help.

**Comment by nkolban** [comment]
May we close this issue?

**Comment by mgleason** [comment]
yes (from my viewpoint)
