### ISSUE TITLE
service advertising not working

### ISSUE THREAD

**Issue by monteslu** [nkolban/esp32-snippets#163]
Just modified the BLE_notify example to add a line to advertise the service:
```
  // Start advertising
  pServer->getAdvertising()->addServiceUUID(SERVICE_UUID);  // <- added this
  pServer->getAdvertising()->start();
```

In your video demo of this example sketch with web bluetooth you had to filter by name and specify `optionalServices` with the service uuid.

When a BLE peripheral advertises a service, you can just filter by `services` without a name or the optionalServices property.

I have a sketch for the Arduino 101/ TinyTile that has a working service advertisement:  https://github.com/monteslu/ble-io/blob/master/arduino/curie_plus/curie_plus.ino#L127
(This sketch exposes a generic GPIO service I've been connecting to for johnny-five/nodebots)

Here's the two peripherals (curie chip device and esp32) viewed using the android NRF Connect app from android:
![screenshot_20171102-164924](https://user-images.githubusercontent.com/423800/32362093-b9dea180-c023-11e7-851a-633c50efe275.png)
As you can see, the curie device is advertising a service uuid, and the esp32 isn't.  Is this a bug, or perhaps am I missing a step?

btw, thanks for creating ESP32_BLE_Arduino !

**Comment by chegewara** [comment]
@monteslu see this https://github.com/nkolban/esp32-snippets/issues/144#issuecomment-340185708

Short story, your device name is too long. You have to make it max 5 characters long. If it wont help please get back and we will work on it.

**Comment by monteslu** [comment]
fast response :) 
thanks, @chegewara  I'll give that a shot

**Comment by monteslu** [comment]
that was it.  thanks!

**Comment by devinsewell** [comment]
Try adding pAdvertising->addServiceUUID(pService->getUUID()); before pAdvertising->start();
