### ISSUE TITLE
undefined reference to `app_main

### ISSUE THREAD

**Issue by vishnunaik** [nkolban/esp32-snippets#171]
when I am running make all in command window I am getting this error as:
![screenshot from 2017-11-06 12-21-54](https://user-images.githubusercontent.com/32255022/32428701-27645cec-c2ed-11e7-828f-fddd779c7991.png)

I tried to change the code from extern void app_main(void) as  extern "C" void app_main(void); in cpu_start.c file. Still id didn't work.

please help out with this.
Thank you.

**Comment by chegewara** [comment]
Please show output of: ll main

**Comment by vishnunaik** [comment]
@chegewara  when I am typing in command window: II main, it giving as command not found.

**Comment by chegewara** [comment]
then ls -al main

**Comment by vishnunaik** [comment]
![screenshot from 2017-11-06 12-41-13](https://user-images.githubusercontent.com/32255022/32429269-d5f0d342-c2ef-11e7-8d4b-370a0f3cdf1a.png)

**Comment by chegewara** [comment]
Im guessing you just copied SampleClient.cpp from example folder to main folder. Esp-idf application requires entry point to start, by default it is void app_main(). You have few options now. 

1. create main.cpp with this code:
```
extern void SampleClient();
extern "C" {
void app_main();
}
void app_main(){
SampleClient();
}
```
2. at the end of SampleClient.cpp add:
```
extern "C" {
void app_main();
}
void app_main(){
SampleClient();
}
```
There is few other options but those 2 are simplest.

**Comment by vishnunaik** [comment]
Wow @chegewara your awesome it is working now. I am able to run the program.
Thank you for your support.
