### ISSUE TITLE
Mongoose incorrect platform

### ISSUE THREAD

**Issue by wouterdevinck** [nkolban/esp32-snippets#176]
On this line: 
https://github.com/nkolban/esp32-snippets/blob/412f9d2e32172d37d0fdbeeb0a3c3d7240df4c1e/mongoose/webserver/main/component.mk#L9

-DCS_PLATFORM=3
should be replaced with
-DCS_PLATFORM=15

According to mongoose.h:
#define CS_P_ESP32 15
#define CS_P_ESP8266 3

**Comment by nkolban** [comment]
Thank you sir changes made.  Close as needed.
