### ISSUE TITLE
Create dump() for BLEScanResults

### ISSUE THREAD

**Issue by nkolban** [nkolban/esp32-snippets#185]
When we perform a BLE Scan to find devices in range, we get back an object called BLEScanResults() which is a holder for found BLE devices.  We can iterate over the content.  However, what keeps coming up is the idea that we simply want to dump() the contents to the console.  A new method called dump() has been added to BLEScanResults to dump the found devices to the log.

**Comment by zoobab** [comment]
I am trying to call dump(), any example besides getCount()?

I tried the following:

```
void setup() {
  Serial.begin(115200);
  Serial.println("Scanning...");

  BLEDevice::init("");
  BLEScan* pBLEScan = BLEDevice::getScan(); //create new scan
  pBLEScan->setAdvertisedDeviceCallbacks(new MyAdvertisedDeviceCallbacks());
  pBLEScan->setActiveScan(true); //active scan uses more power, but get results faster
  BLEScanResults foundDevices = pBLEScan->start(scanTime);
  Serial.println("Dumping: ");
  Serial.println(foundDevices.dump());
  Serial.println("Scan done!");
}
```
But it does not compile.

**Comment by chegewara** [comment]
When you run your code you should get this code running after foundDevices.dump():
https://github.com/nkolban/esp32-snippets/blob/master/cpp_utils/BLEAdvertisedDevice.cpp#L490-L508
