### ISSUE TITLE
Log level makes difference

### ISSUE THREAD

**Issue by chegewara** [nkolban/esp32-snippets#189]
Im trying to run SampleServer with multiple characterisyics with the same UUID. I have 2 characteristics, each characteristic has 3 different descriptors. More or less it works until i switch log level. With log level verbose works, with log level debug or lower it crash on first ESP_GATTS_ADD_CHAR_EVT event with error in getService()->getHandle().

**Comment by nkolban** [comment]
Would you happen to have a small sample that illustrates the problem.  I believe you have supplied enough information for someone else to code it up ... but it sounds like you may have a test app to hand?

**Comment by chegewara** [comment]
Just wanted to post example with code to recreate this issue but seems its fixed already.
