### ISSUE TITLE
Nice icons request

### ISSUE THREAD

**Issue by chegewara** [nkolban/esp32-snippets#192]
Its not issue, more like request to users. We need some cool icons to css in ESP32_Explorer project. If anyone have some, or have links to any, please share with us:
![client](https://user-images.githubusercontent.com/1406020/32703669-6fab11c4-c7f9-11e7-86d4-0a92cafb10df.jpg)

**Comment by nkolban** [comment]
I recommend we use this icon search engine ...

https://www.iconfinder.com/

and select icons that are free and don't have any license restrictions (at all)
