### ISSUE TITLE
BLE beacon advertising service UUID

### ISSUE THREAD

**Issue by menesesleonardo** [nkolban/esp32-snippets#195]
I'm following this example for nrf52 boards for the development of a platform for indoor location using Arduino.

[https://github.com/adafruit/Adafruit_nRF52_Arduino/tree/master/libraries/Bluefruit52Lib/examples/Projects/rssi_proximity](url)

There, as you can see, all the peripheral devices advertise a 128-bit service UUID with flag 0x07 from bluetooth GAP specificcations.
![nrf52 1](https://user-images.githubusercontent.com/33615982/32743584-d3f0396c-c87a-11e7-94d0-d44a434bf9de.png)

![nrf52 clone](https://user-images.githubusercontent.com/33615982/32743601-ddbf3240-c87a-11e7-8500-50cb863c52b4.png)

[https://www.bluetooth.com/specifications/assigned-numbers/generic-access-profile](url)

Then, a central device filters peripherals and sorts those who have that specific UUID according to their rssi.

I wanted to make my ESP32 A PERIPHERAL, BUT When I created a BLE server with an ESP32 board, uploading this example from ESP32 Arduino BLE library, 

[https://github.com/nkolban/ESP32_BLE_Arduino/tree/master/examples/BLE_server](url)

The advertised UUID doesn't have this flag and looks like an unknown service, here are the screenshots
![esp32 1](https://user-images.githubusercontent.com/33615982/32743489-924c50cc-c87a-11e7-8658-90c890c7d58e.png)

![esp32 unknown service](https://user-images.githubusercontent.com/33615982/32743508-9d8b46aa-c87a-11e7-82c4-21665400fef9.png)

So the Central device doesn't recognize it at all.

I appreciate any help. Thanks

**Comment by chegewara** [comment]
BLE_server is general purpose example. From BLE specification you can learn that advertising packet has to be 31 bytes or less in total. What you can see on first screenshot you provided is:
- type 0x01 - flags, length 2 bytes,
- type 0x0A - TX power, length 2 bytes,
- type 0x07 - advertised 128 bit UUID, length 17 bytes, 1 byte + 16 bytes UUID,
- type 0x09 - name, length 12 bytes.

On screenshot from BLE_server you have more types of advertised data, in such there is no space for UUID. What you can do is:
- shorten device name or even leave it empty string: BLEDevice::init("")
- type 0x12, i have no idea where is it from. Its slave connection interval range,
- you need to add `pAdvertising->addServiceUUID(UUID);` where UUID is the uuid you want to be advertised and central will looking for, it may be `UUID =  BLEUUID(pService->getUUID())`.


If you will have more questions or issue you are welcome to ask.

**Comment by menesesleonardo** [comment]
Hello @chegewara , thanks for your help, unfortunately no luck.

Here is the link to the code
https://pastebin.com/u8AKcuqP

![screenshot_20171113-145310](https://user-images.githubusercontent.com/33615982/32746280-18a05094-c883-11e7-9902-16fc80d29056.png)

As i showed before, i'd like to remove all that advertised data and leave only what is needed for the application. 
* 0x01
* 0x0A
* 0x07
* 0x09

**Comment by chegewara** [comment]
Try like that:
```
  BLEAdvertising *pAdvertising = pServer->getAdvertising();
  pAdvertising->addServiceUUID(SERVICE_UUID);
 pAdvertising->start();
```

One more question. You provided link to ESP_32BLE_Arduino, its the repo where you from have this example. Is this repo where you from have BLE library? Because it is very outdated, and in this case my advise is to read this https://github.com/nkolban/esp32-snippets/blob/master/cpp_utils/ArduinoBLE.md, especially Replace paragraph.

**Comment by menesesleonardo** [comment]
@chegewara it worked!!!! thank you!

![screenshot_20171113-152147](https://user-images.githubusercontent.com/33615982/32747434-b4d674fe-c886-11e7-8b19-685883b54ffd.png)

I don't know why it publishes all the information twice, but the central can find it anyway.

Also, about the library, I followed windows instructions from the core page just one week ago,
https://github.com/espressif/arduino-esp32

Do you suggest I still need to delete and change all that?

I think this issue can be closed. I'll do it with your answer.

Thanks

**Comment by chegewara** [comment]
It is advertised twice because its standard advertising and response advertising. It is not required but it is implemented in this library. Also Standard advertising and response advertising can differ, but again, in this library both have the same value.

It is not required to change library, but if you are using latest esp-idf then its good to change library with this repo. It is still developed and all the time new features are implemented, also some bugs are fixed.

**Comment by Phando** [comment]
Updating the library and modifying the advertising worked for me, thanks!!!!

**Comment by planevina** [comment]
It's worked for me too. Thanks
