### ISSUE TITLE
BLE.h: No file or Directory found

### ISSUE THREAD

**Issue by mumairanwar92** [nkolban/esp32-snippets#20]
I'm writing a BLE C++ Application following the Kolban's tutorial. I have included all the source files as mentioned in the tutorials, Everyfile is accepted but only one is excluded "BLE.h". the file is present in the include directory but error is still there, I have check the "menuconfig", bluetooth is enabled there. 
A little help would be appreciated.

<img width="1022" alt="terminal" src="https://user-images.githubusercontent.com/9821601/28009849-60e6266e-6576-11e7-8a1d-a6c720b4d23e.png">
<img width="1004" alt="configuration" src="https://user-images.githubusercontent.com/9821601/28009851-6148d8ae-6576-11e7-9e5c-959bc1464a7d.png">
<img width="1590" alt="eclipse" src="https://user-images.githubusercontent.com/9821601/28009850-6144e3f2-6576-11e7-93ec-0bb0b93d790e.png">

**Comment by nkolban** [comment]
Howdy ... my focus this week will be polishing up the documentation and producing samples.  If I may, let me write this up ASAP and post a link to the materials here.  Hopefully it will serve us both.  I'll work with you directly so that you get built what you want and you can give me feedback on how easy to understand the documentation is/will be.

**Comment by mumairanwar92** [comment]
Sure, that would be great. Thankyou. I'll glad if i can in some way.

Sent from iOS
________________________________

**Comment by nkolban** [comment]
Samples and a guide are now up.

**Comment by nkolban** [comment]
Howdy ... is there anything else we can do related to this issue?  Is it ready to be closed out?

**Comment by mumairanwar92** [comment]
Yes, thank for helping, I'm closing this issue.
I'll PM you if I will have any problem. Thanks Again.
