### ISSUE TITLE
Fix Makefile.arduino

### ISSUE THREAD

**Issue by reaper7** [nkolban/esp32-snippets#212]
Please fix Makefile.arduino because BLECharacteristicCallbacks.cpp does not exist
and build lib is not possible

**Comment by nkolban** [comment]
Oooh ... sorry ... I just broke that ... fixing now

**Comment by nkolban** [comment]
Thank you sir ... sorry for the problem and MANY thanks for reporting.  Close when ready or post back if I failed again.

**Comment by reaper7** [comment]
👍
