### ISSUE TITLE
Missing WiFi.h when including BootWifi.h

### ISSUE THREAD

**Issue by SalvaPedraza** [nkolban/esp32-snippets#218]
I am trying to use BootWifi module. I develop in eclipse with esp-idf.
However when including bootwifi.h I get following error:
 fatal error: WiFi.h: No such file or directory
I can bot find "WiFi.h" in any esp-idf moduel. I see though esp_wifi.h
How can I fix it?

**Comment by chegewara** [comment]
You have to add cpp_utils folder to components folder in your project

**Comment by SalvaPedraza** [comment]
Thanks for quick response.
And for all valuable info you are sharing.

**Comment by nkolban** [comment]
Closing for just now, re-open as needed.
