### ISSUE TITLE
BLE_Client crash on server disconnect

### ISSUE THREAD

**Issue by skyng22003** [nkolban/esp32-snippets#225]
First of all, a massive thank you for writing this library.

I have been using the ESP32 on the Arduino IDE with the latest ESP32_BLE library.

I made some modifications to your BLE_Client here's the code is below.

Basically what it is doing it there are 2 services after it connects to the server.
The server sends out notifications on the characteristic
rxUUID("0783b03e-8535-b5a0-7140-a304d2495cb8");
and the other is charUUID("0783b03e-8535-b5a0-7140-a304d2495cba"); which the client can write to.

There is a timeout timer "BLEtimeout" where if the client does not receive any notifications the client initiates a pClient->disconnect and re-scans to connect, this part works fine.

However, if the server initiates a disconnect ie. device is powered off etc the program grinds to a halt.

Here's the printout:
 Notify callback for characteristic 0783b03e-8535-b5a0-7140-a304d2495cb8 of data length 8
Data: 614000040020 //Last notifcation received, server disconnect here
Setting new characteristic value to "Time since boot: 230"
E (252590) BT: bta_gattc_conn_cback() - cif=3 connected=0 conn_id=3 reason=0x0008
connected: 1
doConnect: 0
Scanning: 0
BLETO: 1
Setting new characteristic value to "Time since boot: 240"
//After this there were no more printouts

I don't know if this is related to the other issues raised but I would appreciate your input.

Many Thanks, Sky

Edit: Move code to pastebin:

https://pastebin.com/PEQ2BXEv

**Comment by nkolban** [comment]
Many thanks for the detailed report.  Lets see if we can't capture a trace from your environment.  There are some instructions found here:

https://github.com/nkolban/esp32-snippets/blob/master/cpp_utils/ArduinoBLE.md#switching-on-debugging

Switching this on, rebuilding the code and re-running should produce trace of what is going inside the BLE libraries.  From there, we can take a look see and see if we get an indication of what might be going on.

**Comment by skyng22003** [comment]
Thank you for your prompt reply, below is what I got from turning verbose debug on:
[D][BLEDevice.cpp:105] gattClientEventHandler(): gattClientEventHandler [esp_gatt_if: 3] ... ESP_GATTC_NOTIFY_EVT
[D][BLEUtils.cpp:1344] dumpGattClientEvent(): GATT Event: ESP_GATTC_NOTIFY_EVT
[D][BLEUtils.cpp:1451] dumpGattClientEvent(): [conn_id: 0, remote_bda: f5:e1:02:80:05:f4, handle: 18 0x12, value_len: 8, is_notify: 1]
[D][BLERemoteCharacteristic.cpp:173] gattClientEventHandler(): Invoking callback for notification on characteristic Characteristic: uuid: 0783b03e-8535-b5a0-7140-a304d2495cb8, handle: 18 0x12, props: broadcast: 0, read: 0, write_nr: 0, write: 0, notify: 1, indicate: 0, auth: 0
Notify callback for characteristic 0783b03e-8535-b5a0-7140-a304d2495cb8 of data length 8
Data: 614000040019
E (78442) BT: bta_gattc_conn_cback() - cif=3 connected=0 conn_id=3 reason=0x0008
[D][BLEDevice.cpp:105] gattClientEventHandler(): gattClientEventHandler [esp_gatt_if: 3] ... ESP_GATTC_WRITE_CHAR_EVT
[D][BLEUtils.cpp:1344] dumpGattClientEvent(): GATT Event: ESP_GATTC_WRITE_CHAR_EVT
[D][BLEUtils.cpp:1587] dumpGattClientEvent(): [status: ESP_GATT_ERROR, conn_id: 0, handle: 22 0x16]
[D][BLERemoteCharacteristic.cpp:566] writeValue(): << writeValue
connected: 1
doConnect: 0
Scanning: 0
BLETO: 1
[D][BLEDevice.cpp:105] gattClientEventHandler(): gattClientEventHandler [esp_gatt_if: 3] ... ESP_GATTC_DISCONNECT_EVT
[D][BLEUtils.cpp:1344] dumpGattClientEvent(): GATT Event: ESP_GATTC_DISCONNECT_EVT
[D][BLEUtils.cpp:1389] dumpGattClientEvent(): [conn_id: 0, remote_bda: f5:e1:02:80:05:f4]
[D][BLEDevice.cpp:105] gattClientEventHandler(): gattClientEventHandler [esp_gatt_if: 3] ... ESP_GATTC_CLOSE_EVT
[D][BLEUtils.cpp:1344] dumpGattClientEvent(): GATT Event: ESP_GATTC_CLOSE_EVT
[D][BLEUtils.cpp:1359] dumpGattClientEvent(): [status: ESP_GATT_INSUF_AUTHORIZATION, reason:ESP_GATT_CONN_TIMEOUT, conn_id: 0]
Setting new characteristic value to "Time since boot: 66"
[D][BLERemoteCharacteristic.cpp:544] writeValue(): >> writeValue(), length: 19

**Comment by skyng22003** [comment]
That was the end of the print, there were no exception codes though....

**Comment by nkolban** [comment]
That doesn't seem like enough trace ... was there more at the start?  Can you paste the complete set of trace to a pastebin?  We are seeing some errors in the trace ....  these are the errors pushed by the lower level ... which just now simply state "ESP_GATT_ERROR" ... I'm hoping that previous trace will give us more information.

**Comment by skyng22003** [comment]
Sure, let me know if there's anything else I can do
[https://pastebin.com/itsE2J6f](url)

**Comment by nkolban** [comment]
I have an initial guess at what is going on and have created an issue to guard ... see:

https://github.com/nkolban/esp32-snippets/issues/228

At a high level, I think what is happening is that the logic in the app is calling 

```
pRemoteCharacteristic->writeValue(newValue.c_str(), newValue.length());
```

Even though the connection to the BLE Server has now been lost.  It appears that the BLE logic blocks that API call waiting for a response that will never come.  The onus appears to be on the application logic to not attempt to read or write from remote characteristics after an indication that the connection has been dropped.

The BLEClient class has a method on it called "isConnected" which returns true if we are connected and false otherwise.  What I'd like you to do is test that flag is correct and only attempt to write to the remote characteristic if we are indeed currently connected.

**Comment by skyng22003** [comment]
The code below fixed the issue, many thanks!

Is there an option to configure the "isConnected" timeout? 

 if(pClient->isConnected()==true){
    pRemoteCharacteristic->writeValue(newValue.c_str(), newValue.length());
    Serial.println("Setting new characteristic value to \"" + newValue + "\"");
    //std::string value3 = pRemoteCharacteristic->readValue();
    // Serial.print("Data:");
    //Serial.println(value3.c_str());
    }

**Comment by nkolban** [comment]
This is only a circumvention issue #228 will fix it properly.  Currently there is no "timeout" ... we are either connected or not connected.  No timeout involved.  What I need to do is provide some improvements such as:

1. Throwing an exception when attempting to read or write from a disconnected characteristic.
2. Providing an "onDisconnected" callback

**Comment by skyng22003** [comment]
I see, thank you very much for your help!

**Comment by nkolban** [comment]
Closing for just now
