### ISSUE TITLE
How to write Makefile

### ISSUE THREAD

**Issue by blueMoods** [nkolban/esp32-snippets#234]
For issues: https://github.com/espressif/esp-idf/issues/857 
I add Makefile at esp32-snippets/cpp_utils/tests/BLETests/
The contents of the Makefile are as follows:
PROJECT_NAME := BLETests

COMPONENT_ADD_INCLUDEDIRS := components/include

include $(IDF_PATH)/make/project.mk

But I make failed ,the log are as follows:
/home/baohongde/github/customer/esp32-snippets/cpp_utils/tests/BLETests/build/esp32/libesp32.a(cpu_start.o):(.literal.main_task+0xc): undefined reference to app_main' /home/baohongde/github/customer/esp32-snippets/cpp_utils/tests/BLETests/build/esp32/libesp32.a(cpu_start.o): In functionmain_task':
/home/baohongde/develop/esp-idf/components/esp32/./cpu_start.c:392: undefined reference to `app_main'
collect2: error: ld returned 1 exit status
/home/baohongde/develop/esp-idf/make/project.mk:359: recipe for target '/home/baohongde/github/customer/esp32-snippets/cpp_utils/tests/BLETests/build/BLETests.elf' failed
make: *** [/home/baohongde/github/customer/esp32-snippets/cpp_utils/tests/BLETests/build/BLETests.elf] Error 1

Could you please help to find where i was wrong. And how to write Makefile.

**Comment by chegewara** [comment]
Im assuming your main file is cpp, then you need to add extern in it because linker is expecting that `void app_main(void)` is plain C function. Just add this in you main.cpp or whatever you call it:

```
extern "C" {
    void app_main(void);
}
```

**Comment by blueMoods** [comment]
@chegewara Thanks,  this sentence already exists in my main.cpp. but stil failed.

**Comment by chegewara** [comment]
Ok then. Do you have components.mk file in your main subfolder?

**Comment by chegewara** [comment]
Basicaly in most cases its just an empty file

**Comment by blueMoods** [comment]
Like the picture, I add the empty file , but still make failed
![screenshot from 2017-11-28 17-06-46](https://user-images.githubusercontent.com/30062326/33311168-e0b17b30-d45e-11e7-97dc-33ba2b4e8f5d.png)

**Comment by chegewara** [comment]
You need to use this as start of your project:
https://github.com/espressif/esp-idf-template
Then copy main.cpp and all Sample files you want to use, like SampleServer.cpp or SampleClient.cpp to main subfolder, add subfolder components in template project and copy or symlink into components cpp_utils. Then you will have tree like this:
![make](https://user-images.githubusercontent.com/1406020/33311851-5ea778de-d426-11e7-99a2-06048a6b1477.JPG)

**Comment by nkolban** [comment]
Thanks for the questions mr @blueMoods  ... delighted that we were able to help you out.  When satisfied, please close this issue.  If you have other puzzles related to using the cpp_utils project, please go ahead and create any new issues you need.
