### ISSUE TITLE
#include "sdkconfig.h" - No such directory

### ISSUE THREAD

**Issue by RobertYuwono** [nkolban/esp32-snippets#253]
```
C:\Users\Documents\Arduino\libraries\ESP32_BLE_Arduino\src/BLEDevice.h:10:23: fatal error: sdkconfig.h: No such file or directory
 #include "sdkconfig.h"
                       ^
compilation terminated.
exit status 1
Error compiling for board NodeMCU 1.0 (ESP-12E Module).
```

I got this error, do you have any idea how I can solve it?
Thanks,
Robert

**Comment by nkolban** [comment]
Howdy Robert  .... I'm probably going to need some more context.  What version of Arduino IDE are you using?  When was the last time you refreshed the ESP32-Arduino install?  Are you running a custom build of the BLE C++ classes?  (the latest versions of Arduino-ESP32 contain the BLE C++ classes meaning that you should delete private copies).

**Comment by chegewara** [comment]
But why do you trying to compile this library with esp8266? It wont work.

**Comment by RobertYuwono** [comment]
I am new to this programming world.
I am using  Arduino IDE 1.8.5 and I am using NodeMCU ( new, so never been refreshed).
I am just adding the library directly from the IDE and try to run the scan example.

The target of this:
- try to read estimote beacon using nodeMCU connected to bluetooth module (HC-05).

**Comment by chegewara** [comment]
Most important question is: do you have NodeMCU-32S or NodeMCU 1.0? From logs i can read you have second one or at least this one you are trying to flash.
`Error compiling for board NodeMCU 1.0 (ESP-12E Module).`

**Comment by nkolban** [comment]
Closing for just now.  Re-open as needed.

**Comment by buteomont** [comment]
I know that this is an old thread, but I'm getting the exact same error and pulling out my hair.  I updated to the latest IDE (1.8.8) and the latest ESP32_BLE_Arduino (1.0.1) but neither helped. Would love a pointer to a fix.

**Comment by chegewara** [comment]
Check if you have this file:
`C:\Users\user\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.1\tools\sdk`

**Comment by buteomont** [comment]
Thanks.  In case anyone else is having this problem, there is apparently a conflict between the _expressif ESP32_ board libraries and the _ESP8266 community_ ones.  Removing the latter fixed the problem.  I haven't dug into it deep enough to be more specific.

**Comment by Credesence** [comment]
this error is due to wrong board selection, change it to TinyPICO. problem solved for me

**Comment by CodeWreckPro** [comment]
I tried this but couldn't fix it
i'm getting the error
C:\Users\Rakshiiii\Documents\Arduino\libraries\AsyncTCP-master\src/AsyncTCP.h:26:10: fatal error: sdkconfig.h: No such file or directory
26 | #include "sdkconfig.h"
I installed the library from git repository of me-no-dev.
could you please help me out.

Some insights from you @me-no-dev  would also be really great.

**Comment by me-no-dev** [comment]
you building it for ESP32? because that file do exist for all ESP32 based boards

**Comment by pvelesko** [comment]
For others: I was trying to program ESP8266 whereas my intention was ESP32

**Comment by zagoorland** [comment]
I also have this error and I'm 100% sure I selected correct board.

**Comment by C-PLUS-PLUSandPYTHON** [comment]
Hi, got the same error:

> [!WARNING]
> In file included from C:\Users\docsc\OneDrive\Niko\Elektronik\Arduino\WLAN_BLUETOOTH\BLEmouse_keyboard\BLEmouse_keyboard.ino:1:0:
c:\Users\docsc\Documents\Arduino\libraries\ESP32_BLE_Keyboard/BleKeyboard.h:3:10: fatal error: sdkconfig.h: No such file or directory
 #include "sdkconfig.h"
          ^~~~~~~~~~~~~
compilation terminated.

I tried to make a ble keyboard with esp32.
Board Selected: NodeMCU 1.0 (ESP-12E Module)


Code: 
```c++
#include <BleKeyboard.h>

// First param is name
// Second is manufacturer
// Third is initial batter level
BleKeyboard bleKeyboard("BLE_ESP32", "Arduino", 100);

void setup() {
  Serial.begin(9600);
  Serial.println("Starting, Connecting to Device");
  bleKeyboard.begin();
  while (!bleKeyboard.isConnected()) {
    Serial.print(".");
  }
}

void loop() {
  if (bleKeyboard.isConnected()) {
    Serial.println("Sending Hello World");
    bleKeyboard.println("Hello World!");
    delay(100);
  }
}
```

Things I've already tried:
-use other/example sketches
-reinstall ArduinoBle lib now Version 1.3.7
   and ESP32-BLE-Keyboard now v0.3.0

Thanks in advance!

**Comment by chegewara** [comment]
> ESP-12E Module

Are you sure this is esp32? As far as i know it is esp8266 module

And your issue about missing file, im can you show screenshoot how did you select module from menu?

**Comment by pvelesko** [comment]
> Are you sure this is esp32? As far as i know it is esp8266 module

this was the issue for me

**Comment by C-PLUS-PLUSandPYTHON** [comment]
ah  sorry, youre right, but now I get this
> [!WARNING]
> In file included from c:\Users\docsc\Documents\Arduino\libraries\ESP32_BLE_Keyboard\BleKeyboard.cpp:14:
C:\Users\docsc\AppData\Local\Arduino15\packages\esp32\tools\esp32-arduino-libs\idf-release_v5.1-b6b4727c58\esp32/include/driver/deprecated/driver/adc.h:19:2: warning: #warning "legacy adc driver is deprecated, please migrate to use esp_adc/adc_oneshot.h and esp_adc/adc_continuous.h for oneshot mode and continuous mode drivers respectively" [-Wcpp]
   19 | #warning "legacy adc driver is deprecated, please migrate to use esp_adc/adc_oneshot.h and esp_adc/adc_continuous.h for oneshot mode and continuous mode drivers respectively"
      |  ^~~~~~~
c:\Users\docsc\Documents\Arduino\libraries\ESP32_BLE_Keyboard\BleKeyboard.cpp: In member function 'void BleKeyboard::begin()':
c:\Users\docsc\Documents\Arduino\libraries\ESP32_BLE_Keyboard\BleKeyboard.cpp:105:19: error: cannot convert 'std::string' {aka 'std::__cxx11::basic_string<char>'} to 'String'
  105 |   BLEDevice::init(deviceName);
      |                   ^~~~~~~~~~
      |                   |
      |                   std::string {aka std::__cxx11::basic_string<char>}
In file included from c:\Users\docsc\Documents\Arduino\libraries\ESP32_BLE_Keyboard\BleKeyboard.cpp:7:
C:\Users\docsc\AppData\Local\Arduino15\packages\esp32\hardware\esp32\3.0.4\libraries\BLE\src/BLEDevice.h:41:27: note:   initializing argument 1 of 'static void BLEDevice::init(String)'
   41 |   static void init(String deviceName);                                                            // Initialize the local BLE environment.
      |                    ~~~~~~~^~~~~~~~~~
c:\Users\docsc\Documents\Arduino\libraries\ESP32_BLE_Keyboard\BleKeyboard.cpp:116:32: error: no matching function for call to 'BLECharacteristic::setValue(std::string&)'
  116 |   hid->manufacturer()->setValue(deviceManufacturer);
      |   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
In file included from C:\Users\docsc\AppData\Local\Arduino15\packages\esp32\hardware\esp32\3.0.4\libraries\BLE\src/BLEServer.h:23,
                 from C:\Users\docsc\AppData\Local\Arduino15\packages\esp32\hardware\esp32\3.0.4\libraries\BLE\src/BLEDevice.h:21:
C:\Users\docsc\AppData\Local\Arduino15\packages\esp32\hardware\esp32\3.0.4\libraries\BLE\src/BLECharacteristic.h:77:8: note: candidate: 'void BLECharacteristic::setValue(uint8_t*, size_t)'
   77 |   void setValue(uint8_t *data, size_t size);
      |        ^~~~~~~~
C:\Users\docsc\AppData\Local\Arduino15\packages\esp32\hardware\esp32\3.0.4\libraries\BLE\src/BLECharacteristic.h:77:8: note:   candidate expects 2 arguments, 1 provided
C:\Users\docsc\AppData\Local\Arduino15\packages\esp32\hardware\esp32\3.0.4\libraries\BLE\src/BLECharacteristic.h:78:8: note: candidate: 'void BLECharacteristic::setValue(String)'
   78 |   void setValue(String value);
      |        ^~~~~~~~
C:\Users\docsc\AppData\Local\Arduino15\packages\esp32\hardware\esp32\3.0.4\libraries\BLE\src/BLECharacteristic.h:78:24: note:   no known conversion for argument 1 from 'std::string' {aka 'std::__cxx11::basic_string<char>'} to 'String'
   78 |   void setValue(String value);
      |                 ~~~~~~~^~~~~
C:\Users\docsc\AppData\Local\Arduino15\packages\esp32\hardware\esp32\3.0.4\libraries\BLE\src/BLECharacteristic.h:79:8: note: candidate: 'void BLECharacteristic::setValue(uint16_t&)'
   79 |   void setValue(uint16_t &data16);
      |        ^~~~~~~~
C:\Users\docsc\AppData\Local\Arduino15\packages\esp32\hardware\esp32\3.0.4\libraries\BLE\src/BLECharacteristic.h:79:27: note:   no known conversion for argument 1 from 'std::string' {aka 'std::__cxx11::basic_string<char>'} to 'uint16_t&' {aka 'short unsigned int&'}
   79 |   void setValue(uint16_t &data16);
      |                 ~~~~~~~~~~^~~~~~
C:\Users\docsc\AppData\Local\Arduino15\packages\esp32\hardware\esp32\3.0.4\libraries\BLE\src/BLECharacteristic.h:80:8: note: candidate: 'void BLECharacteristic::setValue(uint32_t&)'
   80 |   void setValue(uint32_t &data32);
      |        ^~~~~~~~
C:\Users\docsc\AppData\Local\Arduino15\packages\esp32\hardware\esp32\3.0.4\libraries\BLE\src/BLECharacteristic.h:80:27: note:   no known conversion for argument 1 from 'std::string' {aka 'std::__cxx11::basic_string<char>'} to 'uint32_t&' {aka 'long unsigned int&'}
   80 |   void setValue(uint32_t &data32);
      |                 ~~~~~~~~~~^~~~~~
C:\Users\docsc\AppData\Local\Arduino15\packages\esp32\hardware\esp32\3.0.4\libraries\BLE\src/BLECharacteristic.h:81:8: note: candidate: 'void BLECharacteristic::setValue(int&)'
   81 |   void setValue(int &data32);
      |        ^~~~~~~~
C:\Users\docsc\AppData\Local\Arduino15\packages\esp32\hardware\esp32\3.0.4\libraries\BLE\src/BLECharacteristic.h:81:22: note:   no known conversion for argument 1 from 'std::string' {aka 'std::__cxx11::basic_string<char>'} to 'int&'
   81 |   void setValue(int &data32);
      |                 ~~~~~^~~~~~
C:\Users\docsc\AppData\Local\Arduino15\packages\esp32\hardware\esp32\3.0.4\libraries\BLE\src/BLECharacteristic.h:82:8: note: candidate: 'void BLECharacteristic::setValue(float&)'
   82 |   void setValue(float &data32);
      |        ^~~~~~~~
C:\Users\docsc\AppData\Local\Arduino15\packages\esp32\hardware\esp32\3.0.4\libraries\BLE\src/BLECharacteristic.h:82:24: note:   no known conversion for argument 1 from 'std::string' {aka 'std::__cxx11::basic_string<char>'} to 'float&'
   82 |   void setValue(float &data32);
      |                 ~~~~~~~^~~~~~
C:\Users\docsc\AppData\Local\Arduino15\packages\esp32\hardware\esp32\3.0.4\libraries\BLE\src/BLECharacteristic.h:83:8: note: candidate: 'void BLECharacteristic::setValue(double&)'
   83 |   void setValue(double &data64);
      |        ^~~~~~~~
C:\Users\docsc\AppData\Local\Arduino15\packages\esp32\hardware\esp32\3.0.4\libraries\BLE\src/BLECharacteristic.h:83:25: note:   no known conversion for argument 1 from 'std::string' {aka 'std::__cxx11::basic_string<char>'} to 'double&'
   83 |   void setValue(double &data64);
      |                 ~~~~~~~~^~~~~~

I already got that before... I tested it in the past

**Comment by chegewara** [comment]
This time its in your code and lack of knowledge.
You should read logs:
```
BleKeyboard.cpp:105:19: error: cannot convert 'std::string' {aka 'std::__cxx11::basic_string'} to 'String'
...
BLEDevice::init(deviceName); <--- what is the type of "deviceName"
```

**Comment by C-PLUS-PLUSandPYTHON** [comment]
How Canon I fix it? I Downloaded the lib from the official repo
