### ISSUE TITLE
UART example does not compile.

### ISSUE THREAD

**Issue by pbecchi** [nkolban/esp32-snippets#259]
Trying to compile UART example I get this error:

BLE_uart.ino: 107:24: error: 'class BLECharacteristic' has no member named 'isReadyForData
   if (pTxCharacteristic->isReadyForData())

What can I do?

**Comment by nkolban** [comment]
Howdy @pbecchi 

This logic was written by Mr @Sepp62 ... paging him for a consult.  We are discussing the story in #209 which is where this logic was introduced.  Reading/reviewing the code that was added, I'm afraid I'm not yet getting it.  That doesn't mean it is wrong/bad/broken ... just that I don't yet understand it.  See the latest posts in #209.  We'll get clarification soon.

**Comment by chegewara** [comment]
Strange, it is working for me with BLE_notify example (with issues complaining about c++ exceptions of course).

**Comment by pbecchi** [comment]
Oh ...sorry...compiled is using the wrong library ....on esp32-arduino there is a duplicate of BLEcharacteristic.h.

**Comment by nkolban** [comment]
Closing for just now.  Re-open as needed.
