### ISSUE TITLE
Disable BLE

### ISSUE THREAD

**Issue by quanvuee** [nkolban/esp32-snippets#273]
Hi.
How can I disable bluetooth?
I use IDF function "esp_bluedroid_disable" but it don't work.
I'm looking for disable function in your lib "ESP32_BLE_Arduino" but I can't find any thing.
Hope you can help me because it's very important with me now. I already ask in esp32.com but no one answer.
Thank so much!

**Comment by chegewara** [comment]
Did you see this SampleBLE code? I think its what you need
https://github.com/espressif/arduino-esp32/blob/1407654c52dcf473b28df513a94afd294e3ca819/libraries/SimpleBLE/src/SimpleBLE.cpp#L95-L103
