### ISSUE TITLE
GeneralUtils hexdump

### ISSUE THREAD

**Issue by chegewara** [nkolban/esp32-snippets#277]
Will be this code optimized if we use esp_log_buffer_hex instead stringstream?
https://github.com/nkolban/esp32-snippets/blob/master/cpp_utils/GeneralUtils.cpp#L215

http://esp-idf.readthedocs.io/en/latest/search.html?q=esp_log_buffer_hex&check_keywords=yes&area=default

**Comment by nkolban** [comment]
If we look at the source of the line you referenced in the original post in this thread you'll find it has been commented out ... the current HexDump() is here:

https://github.com/nkolban/esp32-snippets/blob/master/cpp_utils/GeneralUtils.cpp#L293

... and that is pretty optimal.  Not a stringstream in sight.  What we want to do is examine a dumped buffer from ESP32 and a dumped buffer from GeneralUtils.  If they look the same or are close then we get rid of HexDump from general utils and call it good.  I'm not a fan of duplicate functions for no reason so if ESP-IDF has added a good hexdump ... then we shouldn't.
