### ISSUE TITLE
BLEDescriptor and BLERemoteDescriptor upgrade request

### ISSUE THREAD

**Issue by chegewara** [nkolban/esp32-snippets#285]
Thanks to last findings we realized there is some inconsistency between documentation on bluetooth.com and real data that is required to send if we want to turn on/off notifications and/or indications in descriptor 2902. That leads us to situation when we need sometimes to send 16 bit value. It would be nice to have overloaded function `writeValue(uint16_t)`.

**Comment by nkolban** [comment]
Howdy ... can you elaborate.  Can you explain in more details the inconsistency that you mentioned?

**Comment by chegewara** [comment]
Inconsistency:
- at first i just tought so there is value uint8 in documentation
- now i know there is uint16, but i dont see any information about bytes order.
