### ISSUE TITLE
Handle white-list processing

### ISSUE THREAD

**Issue by nkolban** [nkolban/esp32-snippets#291]
While reading this book ... http://shop.oreilly.com/product/0636920033011.do

I was reading about "White Lists" ... and was then looking in the ESP32 docs for related APIs and found

* http://esp-idf.readthedocs.io/en/latest/api-reference/bluetooth/esp_gap_ble.html#_CPPv228esp_ble_gap_update_whitelistb13esp_bd_addr_t
* http://esp-idf.readthedocs.io/en/latest/api-reference/bluetooth/esp_gap_ble.html#_CPPv230esp_ble_gap_get_whitelist_sizeP8uint16_t

Since we have APIs at the ESP-IDF that are exposed ... let us now investigate how we might expose and use these through the C++ classes.

**Comment by chegewara** [comment]
Another step in ble security

**Comment by nkolban** [comment]
New code/functions added:

* `BLEAdvertising::setScanFilter()`
* `BLEDevice::whiteListAdd()`
* `BLEDevice::whiteListRemove()`

No breaking changes and no changes in existing apps introduced by these functions.
