### ISSUE TITLE
Suggested enhancement for cpp_utils/json

### ISSUE THREAD

**Issue by rweller59** [nkolban/esp32-snippets#298]
I keep adding these changes every time I update cpp_utils so hoping we can just add to library...

json.cpp
/**
 * @brief Convert the JSON object to an unformatted string.
 * @return A JSON string representation of the object.
 */
std::string JsonArray::toStringUnformatted() {
	char *data = cJSON_PrintUnformatted(m_node);
	std::string ret(data);
	free(data);
	return ret;
} // toStringUnformatted

/**
 * @brief Convert the JSON object to an unformatted string.
 * @return A JSON string representation of the object.
 */
std::string JsonObject::toStringUnformatted() {
	char *data = cJSON_PrintUnformatted(m_node);
	std::string ret(data);
	free(data);
	return ret;
} // toStringUnformatted

json.j (class JsonObject and JsonArray)
	std::string toStringUnformatted();

**Comment by nkolban** [comment]
To hear is to obey.  Changes added.  Please review and if delighted close out the issue ... and if not, let us know what we can change next.

**Comment by rweller59** [comment]
Works for me. thanks for quick response.
