### ISSUE TITLE
Add BLE Security to Arduino library

### ISSUE THREAD

**Issue by rucindrea** [nkolban/esp32-snippets#302]
It would be great to have support and an example for using BLE Security (implemented in #293) in the Arduino library as well

**Comment by nkolban** [comment]
We are currently awaiting a new refresh of the Arduino-ESP32 libraries from the awesome mr @me-no-dev 

Until we get a refresh of the Arduino-ESP32 libraries which includes switching on C++ exception handling, I'm afraid we don't have the ability to re-publish any new builds from BLE C++ classes.  Our hope is that the Arduino-ESP32 libraries will be refreshed before too long.
