### ISSUE TITLE
Provide signatures for public functions that can take strings as opposed to BLEUUIDs

### ISSUE THREAD

**Issue by nkolban** [nkolban/esp32-snippets#31]
There are public functions today that take BLEUUIDs ... provide alternatives/over-rides that accept strings.

For example, where we have a function that looks like:

```
void foo(BLEUUID uuid)
```

provide an additional signature that looks like:

```
void foo(char* uuid) {
   foo(BLEUUID(std::string(uuid)));
}
```

and
```
void foo(std::string uuid) {
   foo(BLEUUID(uuid));
}
```

**Comment by copercini** [comment]
Working on it =)

**Comment by nkolban** [comment]
@copercini provided an excellent implementation that has been pushed and merged.  I think we can close this issue for the time being.
