### ISSUE TITLE
HttpRequest::getQuery() does not return query params 

### ISSUE THREAD

**Issue by yaoyogi** [nkolban/esp32-snippets#310]
The method just sets the query string as an empty string so the returned map is always empty.

This code gets the query string from the path and then the rest of the code seems to work:

```
std::map<std::string, std::string> HttpRequest::getQuery() {
	// Walk through all the characters in the query string maintaining a simple state machine
	// that lets us know what we are parsing.
	std::map<std::string, std::string> queryMap;
	std::string possibleQueryString = getPath() ;
	int qindex = possibleQueryString.find_first_of("?") ;
	if (qindex < 0) {
		ESP_LOGD(LOG_TAG, "No query string present") ;
		return queryMap ;
	}
	std::string queryString = possibleQueryString.substr(qindex + 1, -1) ;
	ESP_LOGD(LOG_TAG, "query string: %s", queryString.c_str()) ;
...
```

**Comment by nkolban** [comment]
Studying now ...

**Comment by nkolban** [comment]
Wow!!  Thank you again my friend.  That was appalling on my end.  What a blunder.  I have made exactly the changes you suggested and compiled cleanly.  I have pushed the changes through to the repository.  Again THANK YOU kind sir.

**Comment by yaoyogi** [comment]
Thank you for applying fix.
