### ISSUE TITLE
ESP_BLE_Arduino 0.4.8 & missing HIDTypes.h file

### ISSUE THREAD

**Issue by reaper7** [nkolban/esp32-snippets#365]
1.
For external library: https://github.com/nkolban/ESP32_BLE_Arduino I got this error message:
```
C:\PROGRAMY\arduino_projekty\libraries\ESP32_BLE_Arduino\src\BLEHIDDevice.h:18:22: fatal error: HIDTypes.h: No such file or directory
```

---------------

2.
and additional/second, building via Makefile.arduino skips **BLE2904.*** files, 
needed for https://github.com/nkolban/esp32-snippets/blob/master/cpp_utils/BLEHIDDevice.cpp#L11

**Comment by chegewara** [comment]
This file you need to copy to library folder, sorry for inconvenience, i must have forgot to add it to makefile:
https://github.com/nkolban/esp32-snippets/blob/master/cpp_utils/HIDTypes.h

Thanks for reporting and i hope you like hid library and have it useful.

**Comment by reaper7** [comment]
new 0.4.9 contains all necessary files 👍 
but still needs a solution for https://github.com/nkolban/esp32-snippets/issues/368
