### ISSUE TITLE
Makefile.arduino

### ISSUE THREAD

**Issue by jestebanes** [nkolban/esp32-snippets#37]
Hello Neil, great job you are doing with esp32

In the last commit, you change the name of BLE.h and BLE.cpp to BLEDevice.h and BLEDevice.cpp, but in Makefile.arduino you forgot to change those names.

Thank you and best regards.

**Comment by nkolban** [comment]
Thank you kind sir.  Change made and pushed.  That was a stupid error on my part and demonstrated that I didn't test.  The lesson here (for me) is don't be hubristic and assume that all is well.  I tested with ESP-IDF and treated Arduino like a second class citizen.  I'm going to try very hard to make sure I test with Arduino as well.
