### ISSUE TITLE
Fixes to example files

### ISSUE THREAD

**Issue by lambosprit** [nkolban/esp32-snippets#413]
Hi Neil.
Firstly thanks for all the fantastic work you've done on this. 
I thought I'd post to try to add something back and help people avoid some of the troubles I've had.
I tried to use the BLE_Client and BLE_Server ino example files to connect two ESP32's together but although they found each other the client never discovered the server's service UUID. I then found this link [https://www.esp32.com/viewtopic.php?f=19&t=4161] which explained the problem so I ask if you could update the examples to fix the problems out lined in the link.
I had to change the BLE_Server example because it uses the name MyESP32 which is too long and it misses the line pServer->getAdvertising()->addServiceUUID(serviceUUID); before the pAdvertising->start();. Once I added those lines and matched up the UUID's in both files the examples worked perfectly together.

**Comment by hansmbakker** [comment]
Hi @lambosprit 
great that you want to share your findings! I think a better way to share these improvements is through a [pull request](https://github.com/nkolban/esp32-snippets/pulls).

Would you mind creating one and closing this issue so that the issue list can be cleaned out?

cc @chegewara
