### ISSUE TITLE
Building curl

### ISSUE THREAD

**Issue by Renata27** [nkolban/esp32-snippets#42]
Hi @nkolban ,

With your config files for building curl for ESP IDF - ESP 32, I could get my code working.

But now, after downloading the newest curl from github, I get this issue:
https://github.com/curl/curl/issues/1827

![screenshot 2017-08-24 20 38 54](https://user-images.githubusercontent.com/29973991/29712776-c7703d5e-899b-11e7-97f0-ee5fbd29d8a2.png)

![captura de tela 2017-08-25 13 29 05](https://user-images.githubusercontent.com/29973991/29712710-7657a3c6-899b-11e7-886d-22f1adb78324.png)

Would you please help me understand what I am doing wrong and how to use curl with ESP IDF?

I rely on this for my project to work!

Apreciate your help!!

**Comment by jay** [comment]
@nkolban possibly related:
Changes made for the next curl release in October will require premade configuration files to have the values of SIZEOF_LONG and SIZEOF_CURL_OFF_T due to curl/curl@80d9e35. If you have any related problems please let us know at curl/curl#1816.

**Comment by Renata27** [comment]
Yes, jay. Thank you! Back to previously curl versions, I was able to build. 
But with the new versions, it isn't working, as you saw above!

Best regards.

**Comment by nkolban** [comment]
Howdy guys ... been on vacation for last week ... flying home today.  Normal service/response will resume this evening.

**Comment by nkolban** [comment]
Howdy, again ... sorry tor the delay.  I made the changes recommended by @jay and got a new clean compile.  I have checked in the changes and if we can follow the recipe and try it again, lets see how far we get now.

**Comment by Renata27** [comment]
Thank you @nkolban ! I am going to give that a try and come back to report!

**Comment by Renata27** [comment]
Excellent dear @nkolban !

Thank you for your effort and quick response!
I am very glad to have contacted you, because you have saved my life/file again!

See you!

**Comment by nkolban** [comment]
Howdy @Renata27  he he he ... hopefully not your "life" ...
Glad all is well ... come back anytime with bug reports and we'll try and knock them out quickly and for questions, use the ESP32 forum at esp32.com.

Close this issue when happy.
