### ISSUE TITLE
how to write large data to server from esp32 ble client?

### ISSUE THREAD

**Issue by programmer131** [nkolban/esp32-snippets#429]
hi! thanks for the library and all the example codes, I've tested BLE Client example and it works fine, is it possible to write large data? for example 10KB? I'm unable to find information for that, for example how much to wait before sending next chunk? how much maximum chunk size possible?

**Comment by chegewara** [comment]
https://esp32.com/viewtopic.php?f=2&t=2221&p=21286#p21286

**Comment by programmer131** [comment]
thanks, already got it working, successfully sent 20KB in few seconds.
