### ISSUE TITLE
BLEEddystoneTLM.cpp doesn't compile without Arduino.h

### ISSUE THREAD

**Issue by thomasvdwege** [nkolban/esp32-snippets#447]
BLEEddystoneTLM.cpp doesn't compile when you don't have an Arduino environment on your pc. Could this be fixed? @pcbreflux made the file, I don't think the cpp-utils are supposed to break when you don't have Arduino installed.

For anyone encountering this issue, simply commenting the whole BLEEddystoneTLM.cpp file works.

**Comment by chegewara** [comment]
Or just deleting it

**Comment by nkolban** [comment]
I have pulled these files and moved them into the cpp_utils/onhold directory.   Thank you mr @thomasvdwege for reporting and sorry for the issue.  We should always have a clean build of cpp_utils without any trace of Arduino.   I also didn't find any documentation in the source to explain these source files.  I'm a huge fan of mr @pcbreflux  work and I hope he will come back and clarify the files.  If they are samples, then we can include them in some samples folder as opposed to being in the core build path of the BLE and cpp_utils library.
