### ISSUE TITLE
Simple task.h question

### ISSUE THREAD

**Issue by rweller59** [nkolban/esp32-snippets#450]
can I call task.stop() from within the task? Do I need to pass handle to task in order to do this? Do I even need to do this or can I just return from the task?

**Comment by chegewara** [comment]
Yes, you can. I would say you even can call `vTaskDelete(NULL)` from inside that task, but this can cause memory leak, so myTask->stop() is enough.

**Comment by rweller59** [comment]
thanks. so I need to pass the handle to the task?

**Comment by chegewara** [comment]
No, all its required is handled by Task class. Here m_handleTask is filed with data:
https://github.com/nkolban/esp32-snippets/blob/master/cpp_utils/Task.cpp#L75
so if you start task before you try to stop it then m_handleTask wont be nullptr and such this line will be executed:
https://github.com/nkolban/esp32-snippets/blob/master/cpp_utils/Task.cpp#L90

So, all you have to do somhere in your code is:
- create task (Task* myTask = Task())
- start task (myTask->start())
- stop task when its no longer needed (myTask->stop())
- again start task if required (myTask->start())

**Comment by rweller59** [comment]
yes, get that. What I am not clear on is whether or not the task has a handle to itself?

What I'm doing is starting the task, task executes code and when it has completed its routine, deletes itself - the code that started the task doesn't care about the task after task->start().

**Comment by chegewara** [comment]
myTask has handle to itself, and like i said its this line:
https://github.com/nkolban/esp32-snippets/blob/master/cpp_utils/Task.cpp#L75

to delete task you need to execute myTask->stop() somewhere or myTask will stay in loop

**Comment by rweller59** [comment]
got it. thanks
