### ISSUE TITLE
BLE Device and std::string

### ISSUE THREAD

**Issue by jrickard** [nkolban/esp32-snippets#462]
BLEDevice provides some exposed methods that return std::string as output.

BLEDevice::getValue()
BLEDevice::toString()

Arduino simply cannot deal with std::string as it is part of the Standard Template Library.  Arduino does have a String function which is  a little lame and of course best deals with C style string arrays.

These methods appear to be useless in the Arduino implementation, so why are they there?  Or perhaps better phrased "How to deal with output from getValue() and toString();

**Comment by chegewara** [comment]
As to: How to handle?
`getValue().c_str()`

**Comment by jrickard** [comment]
Thanks.  Got it.
