### ISSUE TITLE
Any details on Makefile setup ?

### ISSUE THREAD

**Issue by lakidd** [nkolban/esp32-snippets#5]
Hi kolban
Love your video's on youtube, but in all your examples, you do a 
`make flash monitor` (I think ?) to kick the whole thing off, however there doesn't appear to be a makefile that I can find in the repo.
Any hints ?

**Comment by nkolban** [comment]
Every project that is a user project should be built from this template ...

https://github.com/espressif/esp-idf-template

**Comment by lakidd** [comment]
ah got it thanks...so get the blank template, and copy and paste the code across into it ?

**Comment by nkolban** [comment]
Yes sir ... that's exactly correct.  For every new project, clone the esp-idf-template and use that as the basis for your new work.  Well .. that's what I do and so far it seems to have worked out ok.

**Comment by lakidd** [comment]
Great stuff, thanks and keep up the good work on the books and videos, they
are great !

**Comment by nkolban** [comment]
Closing believed resolved.
