### ISSUE TITLE
SampleScan error and reboot

### ISSUE THREAD

**Issue by vuanh-minh** [nkolban/esp32-snippets#519]
Hi,
I am trying to run the SampleScan.cpp code with my ESP32, building and flashing with Eclipse. But i have a problem which occures after the scan : 

After the scan started, it shows me the differents devices detected, but after, nothing happens, and then, after a few moment, the ESP32 reboot. 

```
`ASSERT_PARAM(-218959118 0), in arch_main.c at line 306
Guru Meditation Error: Core  0 panic'ed (Interrupt wdt timeout on CPU0)
Core 0 register dump:
PC      : 0x40083c9d  PS      : 0x00060834  A0      : 0x8015fdac  A1      : 0x3ffc0700 
0x40083c9d: r_assert_param at ??:?

A2      : 0x00000001  A3      : 0x00000000  A4      : 0x0000f2f2  A5      : 0x60008054 
A6      : 0x3ffc081c  A7      : 0x60008050  A8      : 0x80083c9d  A9      : 0x3ffc06e0 
A10     : 0x00000004  A11     : 0x00000000  A12     : 0x6000804c  A13     : 0xffffffff 
A14     : 0x00000000  A15     : 0xfffffffc  SAR     : 0x00000004  EXCCAUSE: 0x00000005 
EXCVADDR: 0x00000000  LBEG    : 0x40083bd5  LEND    : 0x40083bdc  LCOUNT  : 0x00000000 
0x40083bd5: r_assert_param at ??:?

0x40083bdc: r_assert_param at ??:?

Core 0 was running in ISR context:
EPC1    : 0x40009203  EPC2    : 0x00000000  EPC3    : 0x00000000  EPC4    : 0x40083c9d
0x40083c9d: r_assert_param at ??:?


Backtrace: 0x40083c9d:0x3ffc0700 0x4015fda9:0x3ffc0720 0x40019fb5:0x3ffc0740 0x400466c3:0x3ffc0770 0x400484ae:0x3ffc0790 0x40085ab6:0x3ffc07b0 0x400868fe:0x3ffc07d0 0x4008741b:0x3ffc07f0 0x4008203a:0x3ffc0810 0x400d37ef:0x00000000
0x40083c9d: r_assert_param at ??:?

0x4015fda9: r_platform_reset at ??:?

0x40085ab6: r_lld_evt_end_isr at ??:?

0x400868fe: r_rwble_isr at ??:?

0x4008741b: r_rwbtdm_isr_wrapper at intc.c:?

0x4008203a: _xt_lowint1 at /home/hyvibe/esp/esp-idf/components/freertos/xtensa_vectors.S:1105

0x400d37ef: esp_vApplicationIdleHook at /home/hyvibe/esp/esp-idf/components/esp32/freertos_hooks.c:85


Rebooting...`
```

And i can't get the tag which tells me that the scan is finish.

`
    ESP_LOGI(LOG_TAG, "We found %d devices", scanResults.getCount());
    ESP_LOGI(LOG_TAG, "Scanning sample ended");`

Where is this problem from ? Thank you

**Comment by sebirdman** [comment]
@vuanh-minh I'm seeing this problem as well. Did you ever find a solution?

**Comment by chegewara** [comment]
It may be this issue related:
https://github.com/espressif/esp-idf/issues/2070

**Comment by arunbm123** [comment]
> Hi,
> I am trying to run the SampleScan.cpp code with my ESP32, building and flashing with Eclipse. But i have a problem which occures after the scan :
> 
> After the scan started, it shows me the differents devices detected, but after, nothing happens, and then, after a few moment, the ESP32 reboot.
> 
> ```
> `ASSERT_PARAM(-218959118 0), in arch_main.c at line 306
> Guru Meditation Error: Core  0 panic'ed (Interrupt wdt timeout on CPU0)
> Core 0 register dump:
> PC      : 0x40083c9d  PS      : 0x00060834  A0      : 0x8015fdac  A1      : 0x3ffc0700 
> 0x40083c9d: r_assert_param at ??:?
> 
> A2      : 0x00000001  A3      : 0x00000000  A4      : 0x0000f2f2  A5      : 0x60008054 
> A6      : 0x3ffc081c  A7      : 0x60008050  A8      : 0x80083c9d  A9      : 0x3ffc06e0 
> A10     : 0x00000004  A11     : 0x00000000  A12     : 0x6000804c  A13     : 0xffffffff 
> A14     : 0x00000000  A15     : 0xfffffffc  SAR     : 0x00000004  EXCCAUSE: 0x00000005 
> EXCVADDR: 0x00000000  LBEG    : 0x40083bd5  LEND    : 0x40083bdc  LCOUNT  : 0x00000000 
> 0x40083bd5: r_assert_param at ??:?
> 
> 0x40083bdc: r_assert_param at ??:?
> 
> Core 0 was running in ISR context:
> EPC1    : 0x40009203  EPC2    : 0x00000000  EPC3    : 0x00000000  EPC4    : 0x40083c9d
> 0x40083c9d: r_assert_param at ??:?
> 
> 
> Backtrace: 0x40083c9d:0x3ffc0700 0x4015fda9:0x3ffc0720 0x40019fb5:0x3ffc0740 0x400466c3:0x3ffc0770 0x400484ae:0x3ffc0790 0x40085ab6:0x3ffc07b0 0x400868fe:0x3ffc07d0 0x4008741b:0x3ffc07f0 0x4008203a:0x3ffc0810 0x400d37ef:0x00000000
> 0x40083c9d: r_assert_param at ??:?
> 
> 0x4015fda9: r_platform_reset at ??:?
> 
> 0x40085ab6: r_lld_evt_end_isr at ??:?
> 
> 0x400868fe: r_rwble_isr at ??:?
> 
> 0x4008741b: r_rwbtdm_isr_wrapper at intc.c:?
> 
> 0x4008203a: _xt_lowint1 at /home/hyvibe/esp/esp-idf/components/freertos/xtensa_vectors.S:1105
> 
> 0x400d37ef: esp_vApplicationIdleHook at /home/hyvibe/esp/esp-idf/components/esp32/freertos_hooks.c:85
> 
> 
> Rebooting...`
> ```
> And i can't get the tag which tells me that the scan is finish.
> 
> ` ESP_LOGI(LOG_TAG, "We found %d devices", scanResults.getCount()); ESP_LOGI(LOG_TAG, "Scanning sample ended");`
> 
> Where is this problem from ? Thank you

Did you solve the error
Even I am getting the error
