### ISSUE TITLE
Help in retriving the service data from advertisements

### ISSUE THREAD

**Issue by hiteshpratyushv** [nkolban/esp32-snippets#528]
I am using the esp-idf and I am unable to figure out how to retrieve the service data from esp_ble_gap_cb_param_t variable for a scanned device. It would really helpful if someone can help me with that.
I am able to get the name and address of the device but not the service data

**Comment by chegewara** [comment]
You can study this:
https://github.com/espressif/esp-idf/blob/92c469b5993b001a21970f0e58b25acd3f375807/components/bt/bluedroid/api/include/api/esp_gap_ble_api.h#L555-L697
https://github.com/nkolban/esp32-snippets/blob/af664f01e706dce7c781f660d867eff8f8c83000/cpp_utils/BLEScan.cpp#L88-L127
https://github.com/espressif/esp-idf/blob/aca000869406e35eba0d5fd7064304ba9e5acead/examples/bluetooth/gatt_client/main/gattc_demo.c#L323-L345

**Comment by hiteshpratyushv** [comment]
In the link
https://github.com/espressif/esp-idf/blob/92c469b5993b001a21970f0e58b25acd3f375807/components/bt/bluedroid/api/include/api/esp_gap_ble_api.h#L555-L697
In the data structure **ble_scan_result_evt_param**, there is a **ble_adv** field, Is that the packet ??
I am really new to all this so, sorry if the question is dumb

**Comment by chegewara** [comment]
This is structure that is passed as parameter during this event:
https://github.com/espressif/esp-idf/blob/aca000869406e35eba0d5fd7064304ba9e5acead/examples/bluetooth/gatt_client/main/gattc_demo.c#L324

This is what you are looking for.

**Comment by hiteshpratyushv** [comment]
I got this.
I need the service data for various UUIDS from this
How do I do this ?

**Comment by chegewara** [comment]
https://github.com/nkolban/esp32-snippets/blob/af664f01e706dce7c781f660d867eff8f8c83000/cpp_utils/BLEAdvertisedDevice.cpp#L232-L298

**Comment by hiteshpratyushv** [comment]
Is the **uint8_t* payload** argument the same as the one bellow?

https://github.com/espressif/esp-idf/blob/92c469b5993b001a21970f0e58b25acd3f375807/components/bt/bluedroid/api/include/api/esp_gap_ble_api.h#L584

**Comment by chegewara** [comment]
Yes, _uint8_t* payload_ is _(uint8_t*)param->scan_rst.ble_adv_ which is 
https://github.com/espressif/esp-idf/blob/92c469b5993b001a21970f0e58b25acd3f375807/components/bt/bluedroid/api/include/api/esp_gap_ble_api.h#L584

**Comment by hiteshpratyushv** [comment]
Thank you
