### ISSUE TITLE
Cannot setup MQTT connection to mosquitto broker on RPi

### ISSUE THREAD

**Issue by hiteshpratyushv** [nkolban/esp32-snippets#529]
I am running mosquitto broker on my rpi with SSL and TLS setup with ca.crt, server.crt and server.key .
How can I establish the connection to the mosquitto broker via my esp32 over ssl ?
I am new to this so any help would be helpful.

**Comment by chegewara** [comment]
https://github.com/tuanpmt/espmqtt
