### ISSUE TITLE
BLE connection between ESPs32 

### ISSUE THREAD

**Issue by luizahiginoss** [nkolban/esp32-snippets#533]
I'm trying to connect one ESP as a client and another as a server, to do that I made the service UUID and the characteristic UUID the same. But using your example codes (latest version), client and server do not connect and the client code crashes after line 47 

Serial.println(" - Found our service");

How can I make this connection happens and read the characteristic value? I'm using arduino IDE plataform

**Comment by chegewara** [comment]
When you last time updated arduino-esp32 library and ESP32BLE_library?

**Comment by luizahiginoss** [comment]
Today! I'm using the latest version. Now the connection not even starts. The only alteration that I've made in the code were the UUIDs and the name of the server for "ESP32" 
This is what the serial monitor shows me 

![client](https://user-images.githubusercontent.com/35378889/40505517-d0e5d632-5f6a-11e8-8462-1c499bbcc09b.JPG)

**Comment by chegewara** [comment]
I just tested it and all works with changes in BLE_server:
```
void setup() {
  Serial.begin(115200);
  Serial.println("Starting BLE work!");

  BLEDevice::init("ESP32");
  BLEServer *pServer = BLEDevice::createServer();
  BLEService *pService = pServer->createService(SERVICE_UUID);
  BLECharacteristic *pCharacteristic = pService->createCharacteristic(
                                         CHARACTERISTIC_UUID,
                                         BLECharacteristic::PROPERTY_READ |
                                         BLECharacteristic::PROPERTY_WRITE
                                       );

  pCharacteristic->setValue("Hello World says Neil");
  pService->start();
  BLEAdvertising *pAdvertising = pServer->getAdvertising();
  pAdvertising->addServiceUUID(SERVICE_UUID);    //<--- ADD THIS LINE
  pAdvertising->start();
  Serial.println("Characteristic defined! Now you can read it in your phone!");
}
```

Assuming that client and server UUID's match.

**Comment by luizahiginoss** [comment]
Thanks, it works now!
