### ISSUE TITLE
Support removing services

### ISSUE THREAD

**Issue by jim-ber** [nkolban/esp32-snippets#534]
Currently, there is no way to remove a service that we have added to the server.

That would be useful for applications that change the GATT Server services during runtime.

**Comment by chegewara** [comment]
I will try to add this when i end with 
https://github.com/nkolban/esp32-snippets/issues/532

**Comment by chegewara** [comment]
Sorry it takes so long but i am busy with paid projects. I will try to add this this week, but no promise.

**Comment by chegewara** [comment]
@jim-ber Could you try this before i make PR? 
https://github.com/chegewara/esp32-snippets

**Comment by jim-ber** [comment]
@chegewara I'll do that today. Thanks for all your work!

Let you know what I find.

**Comment by jim-ber** [comment]
I'm making a few changes tonight and i'll let you know.

**Comment by chegewara** [comment]
@jim-ber It looks pretty solid, did you test it with some example code?
I think you can make PR

**Comment by hansmbakker** [comment]
@jim-ber I see you made a PR to fix this, thank you! Could you please close this issue to keep the issue list clean?
