### ISSUE TITLE
BLESecurity - Pairing and connection successful, but not passing keys.  "Non bonding" 

### ISSUE THREAD

**Issue by gourryinverse** [nkolban/esp32-snippets#556]
I've been using an ESP wroom 32 devkit-c (https://www.mouser.com/new/espressif/espressif-esp32-devkitc/), and i'm unable to utilize a BLESecurity pairing that successfully passes a key.  I'm literally copy-pasting the example setup code, and the result is simply the following

I am doing a somewhat non-conventional thing, in using the same code for client and server device.  However, I would like to stress that I have tested this by segregating the code **completely** based on client and server, and the results are the same.  I always get the following behavior:

E (19425) BT: Non bonding: No keys will be exchanged  

I am thoroughly confused.  None of the callbacks are called, and this seems a result of the this underlying mechanism being met:

esp-idf/components/bt/bluedroid/stack/smp/smp_act.c

  99 /*******************************************************************************
 100 ** Function     smp_send_app_cback
 101 ** Description  notifies application about the events the application is interested in
 102 *******************************************************************************/
 103 void smp_send_app_cback(tSMP_CB *p_cb, tSMP_INT_DATA *p_data)
...
 157                 if (!(p_cb->loc_auth_req & SMP_AUTH_BOND)) {
 158                     SMP_TRACE_WARNING ("Non bonding: No keys will be exchanged");
 159                     p_cb->local_i_key = 0;
 160                     p_cb->local_r_key = 0;
 161                 }

Server-side output:

D (19375) BLEServer: >> handleGATTServerEvent: ESP_GATTS_CONNECT_EVT
D (19375) BLECharacteristic: >> handleGATTServerEvent: ESP_GATTS_CONNECT_EVT
V (19385) FreeRTOS: Semaphore giving: name: ConfEvt (0x3ffea934), owner: <N/A>
D (19395) BLECharacteristic: << handleGATTServerEvent
D (19395) BLECharacteristic: >> handleGATTServerEvent: ESP_GATTS_CONNECT_EVT
V (19405) FreeRTOS: Semaphore giving: name: ConfEvt (0x3ffeb2cc), owner: <N/A>
D (19415) BLECharacteristic: << handleGATTServerEvent
I (19415) BTPairingServer: connection received
D (19425) BLEServer: << handleGATTServerEvent
E (19425) BT: Non bonding: No keys will be exchanged
D (19545) BLEUtils: Received a GAP event: ESP_GAP_BLE_AUTH_CMPL_EVT
D (19545) BLEUtils: [bd_addr: 30:ae:a4:44:0f:42, key_present: 0, key: ***, key_type: 0, success: 1, fail_reason: 0, addr_type: ***, dev_type: ESP_BT_DEVICE_TYPE_BLE]
I (19555) BLEDevice: ESP_GAP_BLE_AUTH_CMPL_EVT
I (19555) ServerSecurityCallbacks: Starting BLE work!
I (19565) ServerSecurityCallbacks: size: 12
.... events to pass a message
I (27905) BluetoothTask: RX Queue read: doodlebug

Client side output:

D (107275) BLEDevice: gattClientEventHandler [esp_gatt_if: 4] ... ESP_GATTC_CONNECT_EVT
D (107285) BLEUtils: GATT Event: ESP_GATTC_CONNECT_EVT
D (107285) BLEUtils: [conn_id: 0, remote_bda: 30:ae:a4:42:e9:22]
D (107295) BLEDevice: gattClientEventHandler [esp_gatt_if: 4] ... ESP_GATTC_OPEN_EVT
D (107305) BLEUtils: GATT Event: ESP_GATTC_OPEN_EVT
D (107305) BLEUtils: [status: ESP_GATT_OK, conn_id: 0, remote_bda: 30:ae:a4:42:e9:22, mtu: 23]
I (107315) BTPairingClient: connected to server
V (107325) FreeRTOS: Semaphore giving: name: OpenEvt (0x3ffebe94), owner: connect
V (107325) FreeRTOS: << wait: Semaphore released: name: OpenEvt (0x3ffebe94), owner: connect
E (107325) BT: Security Manager: BTM_SetEncryption busy, enqueue request
D (107335) BLEClient: << connect(), rc=1
E (107345) BT: earlier enc was not done for same device
I (107345) BluetoothTask: Connected to server
I (107355) BTPairingClient: connected to server
D (107385) BLEUtils: Received a GAP event: ESP_GAP_BLE_AUTH_CMPL_EVT
D (107385) BLEUtils: [bd_addr: 30:ae:a4:42:e9:22, key_present: 0, key: ***, key_type: 0, success: 1, fail_reason: 0, addr_type: ***, dev_type: ESP_BT_DEVICE_TYPE_BLE]
I (107395) BLEDevice: ESP_GAP_BLE_AUTH_CMPL_EVT
I (107405) ClientSecurityCallbacks: remote BD_ADDR:
I (107405) ClientSecurityCallbacks: 30 ae a4 42 e9 22 
I (107415) ClientSecurityCallbacks: address type = 0
I (107415) ClientSecurityCallbacks: pair status = success

My init code looks as follows:

261     pDevice = &Device;
262     pDevice->init("BLE Device");
264     pDevice->setEncryptionLevel(ESP_BLE_SEC_ENCRYPT);
265     pMySecurity = new MySecurity();
266     pMySecurity->pBTTask = this;
267     pDevice->setSecurityCallbacks(pMySecurity);
269     pSecurity = new BLESecurity();
271     pSecurity->setKeySize();
272     pSecurity->setAuthenticationMode(ESP_LE_AUTH_REQ_SC_ONLY);
273     pSecurity->setCapability(ESP_IO_CAP_IO);
274     pSecurity->setRespEncryptionKey(ESP_BLE_ENC_KEY_MASK | ESP_BLE_ID_KEY_MASK);
275     pSecurity->setInitEncryptionKey(ESP_BLE_ENC_KEY_MASK | ESP_BLE_ID_KEY_MASK);

My security callback looks as such

11 uint32_t MySecurity::onPassKeyRequest()
 12 {   
 13     uint32_t passkey = 0;
 14     if (pBTTask->isActingClient)
 15     {
 16         ESP_LOGI(CLTSECTAG, "PassKeyRequest");
 17         passkey = 123456;
 18         // TODO: randomize
 19     }
 20     else // is Server
 21     {
 22         ESP_LOGI(SVRSECTAG, "PassKeyRequest");
 23         passkey = 123456;
 24         // TODO: request input
 25     }
 26     return passkey;
 27 }
 28 
 29 void MySecurity::onPassKeyNotify(uint32_t pass_key)
 30 {   
 31     if (pBTTask->isActingClient)
 32     {
 33         ESP_LOGI(CLTSECTAG, "The passkey Notify number:%d", pass_key);
 34     }
 35     else
 36     {
 37         ESP_LOGI(SVRSECTAG, "The passkey Notify number:%d", pass_key);
 38     }
 39     return;
 40 }
 41 
 42 bool MySecurity::onConfirmPIN(uint32_t pass_key)
 43 {   
 44     bool retval = false;
 45     if (pBTTask->isActingClient)
 46     {
 47         ESP_LOGI(CLTSECTAG, "The passkey YES/NO number:%d", pass_key);
 48         vTaskDelay(5000);
 49         retval = true;
 50     }
 51     else
 52     {
 53         ESP_LOGI(SVRSECTAG, "onConfirmPin %d", pass_key);
 54         // TODO: retval
 55     }
 56     return retval;
 57 }
 58
 59 bool MySecurity::onSecurityRequest()
 60 {
 61     bool retval = false;
 62     if (pBTTask->isActingClient)
 63     {
 64         ESP_LOGI(CLTSECTAG, "Security Request");
 65         retval = true;
 66     }
 67     else
 68     {
 69         ESP_LOGI(SVRSECTAG, "On Security Request");
 70         retval = true;
 71     }
 72     return retval;
 73 }
 74 
 75 void MySecurity::onAuthenticationComplete(esp_ble_auth_cmpl_t auth_cmpl)
 76 {
 77     if (pBTTask->isActingClient)
 78     {
 79         if(auth_cmpl.success)
 80         {
 81             ESP_LOGI(CLTSECTAG, "remote BD_ADDR:");
 82             esp_log_buffer_hex(CLTSECTAG, auth_cmpl.bd_addr, sizeof(auth_cmpl.bd_addr));
 83             ESP_LOGI(CLTSECTAG, "address type = %d", auth_cmpl.addr_type);
 84         }
 85         ESP_LOGI(CLTSECTAG, "pair status = %s", auth_cmpl.success ? "success" : "fail");
 86     }
 87     else
 88     {
 89         ESP_LOGI(SVRSECTAG, "Starting BLE work!");
 90         if(auth_cmpl.success)
 91         {
 92             uint16_t length;
 93             esp_ble_gap_get_whitelist_size(&length);
 94             ESP_LOGI(SVRSECTAG, "size: %d", length);
 95         }
 96     }
 97 }

**Comment by chegewara** [comment]
https://github.com/espressif/esp-idf/blob/e676676541ff31b72818246d267b0ccc529cb0d7/examples/bluetooth/gatt_security_server/tutorial/Gatt_Security_Server_Example_Walkthrough.md#setting-security-parameters

You need to change this line:
`272 pSecurity->setAuthenticationMode(ESP_LE_AUTH_REQ_SC_ONLY);
`

**Comment by gourryinverse** [comment]
I feel stupid now, i'm sorry.  Thank you!

**Comment by deponovo** [comment]
Hi,
I am only now learning about BT and BLE and am using an ESP32. I am using Arduino as the programming "language" and would like to include an authentication step before devices (ESP32 as a server and smartphone as client) pair. I have been googling and looking at threads like this one and the security example in the ESP-IDF and could not really understand what must be done. I am sure not to understand things in detail, because I have tried making my own code for the purpose and got the chip restarting constantly (sorry, I have no more code with me now to post here).

Is there some Arduino example somebody could provide on using a password to pair with an ESP32 via BLE? Or maybe some indications or other references?

Thanks

**Comment by chegewara** [comment]
https://github.com/nkolban/esp32-snippets/tree/master/cpp_utils/tests/BLETests/Arduino/security/BLE_server
