### ISSUE TITLE
BLECharacteristic get raw data

### ISSUE THREAD

**Issue by johngull** [nkolban/esp32-snippets#562]
Currently, in BLECharacteristic you can get value only as std::string - ```std::string    getValue();```
But what if I need raw data (can contain zeros in my case).
Is there is a workaround?
If not, will you accept pull request with the new function for this? And how fast it will appear in 'ESP32 BLE Arduino'?

Thanks

**Comment by chegewara** [comment]
@nkolban

**Comment by u4mzu4** [comment]
I was fighting with a similar challenge, but a simple casting to byte, short or uint solved my problem.

**Comment by johngull** [comment]
@u4mzu4 that is not a solution for my case.
I can receive e.g. 0x11110011. When it will be transformed into std::string the last byte 0x11 will be lost.

**Comment by johngull** [comment]
I made additional tests. And seems I was wrong std::string::length() not cut length by zero byte, so existed function is ok.
Sorry for bothering.
