### ISSUE TITLE
hardware address issue

### ISSUE THREAD

**Issue by kapil97** [nkolban/esp32-snippets#572]
I am using your BLE library for ESP32 in arduino ide.
I am able to print the address of all the devices but not of my iBeacon tag.
Please give some solution for the above issue asap.

My iBeacon is CC2541 based HM10 module.

Thanks and Regards
Kamleshwar

**Comment by chrisn-au** [comment]
Kamleshwar,

Does your beacon show up in the nefConnect app ?

**Comment by kapil97** [comment]
Yes, it shows all the information

**Comment by kapil97** [comment]
![whatsapp image 2018-06-20 at 12 26 00 pm](https://user-images.githubusercontent.com/25155755/41642213-4c781db2-7485-11e8-9569-ebe7ac33380b.jpeg)

**Comment by chegewara** [comment]
Try to run scan example code and watch logs. You will see if this ibeacon will be discovered and logs will be printed with or without address.

**Comment by markiv25** [comment]
where are the log files created in it& where are it stored!

**Comment by chegewara** [comment]
Use putty to connect esp32 and print logs. Just remember to change log level to verbose or at least to debug.

**Comment by markiv25** [comment]
we are using Arduino IDE not ESP-IDF so please go through the issue again and carefully.

**Comment by chegewara** [comment]
Thats fine, you can use arduino-ide. In Tools menu you have Core Debug Level, set it to debug or verbose.
Now you can use putty or serial monitor to see logs, like i mention before.

**Comment by chegewara** [comment]
You have nice instructions here:
https://github.com/nkolban/esp32-snippets/blob/master/cpp_utils/ArduinoBLE.md#switching-on-debugging

**Comment by markiv25** [comment]
thank you !! i had seen the logs ,
though could you help me to get the adddress ! & the it is ignorred to!
![screenshot from 2018-06-20 16-28-51](https://user-images.githubusercontent.com/35622055/41654614-a55281e4-74a7-11e8-9937-a9d6bc9eca33.png)

**Comment by chegewara** [comment]
As you can see everything works, beacon is discovered and MAC is printed in logs. Now here you can filter devices by name or by UUID (this is just example how to filter with UUID):
https://github.com/nkolban/ESP32_BLE_Arduino/blob/af865a916795289c8e7e09b091ff2140c33fc3fe/examples/BLE_client/BLE_client.ino#L78

and then get address:
https://github.com/nkolban/ESP32_BLE_Arduino/blob/af865a916795289c8e7e09b091ff2140c33fc3fe/examples/BLE_client/BLE_client.ino#L84

**Comment by markiv25** [comment]
What if we don't know the UUID?
Can we get the MAC without it? because i was able to do so in esp-idf

**Comment by markiv25** [comment]
i tried the client.ino file as you mentioned though it is unable to get the address

**Comment by chegewara** [comment]
How do you know? How did you try to print address to console log when you get it with `pServerAddress = new BLEAddress(advertisedDevice.getAddress());`

**Comment by markiv25** [comment]
yes i tried it & hereby is the screenshots
![screenshot from 2018-06-20 17-34-02](https://user-images.githubusercontent.com/35622055/41657360-cbe319e6-74b0-11e8-8f20-3c1a32223a4f.png)
![screenshot from 2018-06-20 17-38-21](https://user-images.githubusercontent.com/35622055/41657362-ce62b1a4-74b0-11e8-8c37-9fb4d78413c7.png)

**Comment by u4mzu4** [comment]
Try this one:
advertisedDevice.getAddress().toString().c_str()
as above in your code, instead of simple getAddress()

**Comment by chegewara** [comment]
https://github.com/nkolban/esp32-snippets/blob/master/cpp_utils/BLEAdvertisedDevice.cpp#L490

**Comment by markiv25** [comment]
nope nothing !
![screenshot from 2018-06-20 18-14-01](https://user-images.githubusercontent.com/35622055/41659008-c0be1aa2-74b5-11e8-88f8-3a4203b3d8f4.png)
![screenshot from 2018-06-20 18-13-56](https://user-images.githubusercontent.com/35622055/41659010-c2e0c258-74b5-11e8-8221-fc91bbfe07c0.png)

**Comment by chegewara** [comment]
Serial.println("Add **%s**", advertisedDevice.getAddress().toString().c_str());

**Comment by markiv25** [comment]
nothing again
![screenshot from 2018-06-20 18-40-50](https://user-images.githubusercontent.com/35622055/41660372-7e1bfbfc-74b9-11e8-9f66-2c245f48870d.png)

**Comment by markiv25** [comment]
bhai tujhe kuch nahi ata 
though thanks !

**Comment by markiv25** [comment]
thank you friend
4 !

**Comment by chegewara** [comment]
then:
`Serial.printf("Add %s", advertisedDevice.getAddress().toString().c_str());`
or
`Serial.println( advertisedDevice.getAddress().toString().c_str());'

**Comment by markiv25** [comment]
thank you got it!

**Comment by hansmbakker** [comment]
@kapil97 this issue seems solved, could you please close it to keep the issue list clean?

cc @chegewara
