### ISSUE TITLE
Is there a problem with me creating a PR to add support for ESP_BLE_AD_TYPE_NAME_SHORT = 0x08

### ISSUE THREAD

**Issue by chrisn-au** [nkolban/esp32-snippets#573]
Guys,

just before I do it i just wanted to make sure there was no issue in me creating a PR to add support for the ESP_BLE_AD_TYPE_NAME_SHORT type in BLEAdvertisedDevice. The devices that I am using use this field and it would make my down stream processing a lot easier.  If not I will hack because i really don't want to fork

Thanks

**Comment by chegewara** [comment]
Feel free to make PR

**Comment by chrisn-au** [comment]
Cool will do - now I have to learn how to do the fork and create the pull request :-)
