### ISSUE TITLE
ESP32_BLE.a: No such file or directory

### ISSUE THREAD

**Issue by WALLTECH** [nkolban/esp32-snippets#58]
Trying to compile any Arduino BLE examples results in this error: xtensa-esp32-elf-gcc: error: libraries\ESP32_BLE\ESP32_BLE.a: No such file or directory.

**Comment by nkolban** [comment]
Recreated ... over the weekend, I worked on getting the library added to the master Library manager and broke something.  Checking/fixing now.

**Comment by WALLTECH** [comment]
Alright, thanks.

**Comment by nkolban** [comment]
I think it has been corrected. See #56 for details.

**Comment by nkolban** [comment]
@WALLTECH I am hoping that the issue has now been resolved.  We should now be able to install the library from the Arduino IDE Library Manager.

**Comment by WALLTECH** [comment]
Yep, no issues now. Thanks!

**Comment by nkolban** [comment]
Thanks @WALLTECH  ... am closing the issue ... but don't hesitate to re-open if this problem occurs again or open a new issue for any new problems.  I'm tracking what I have to do based on the issues.
