### ISSUE TITLE
Print Characteristic Value to Serial Monitor

### ISSUE THREAD

**Issue by kirawadden** [nkolban/esp32-snippets#596]
I'm using the BLEClient example sketch with my ESP32 in the arduino IDE, and I'm trying to read the value of my characteristic and print to the serial monitor, but I'm getting this:
<img width="339" alt="screen shot 2018-07-06 at 4 14 19 pm" src="https://user-images.githubusercontent.com/35578800/42398431-dc892374-8137-11e8-857b-6fe9723e1f95.png">
this is the code I'm using:
`std::string value = pRemoteChar2->readValue();
    const char *val = value.c_str();
    Serial.print("The myo info characteristic's value is: ");
    Serial.println(val);`

any ideas as to what I am doing wrong? Thanks!

**Comment by chegewara** [comment]
Your code looks good, but here is the question: what have you read from the other device? Is it string or is it binary value? With your code you can only print string messages and with very little change integer values. Im guessing its the case, peripheral you are connecting to and read characteristic value is not sending string but other data (but like always, i may be wrong).

**Comment by kirawa6** [comment]
The characteristic is meant to print the firmware version of my server (the myo armband), so it's definitely possible that the device is sending that in binary/hexadecimal. I'm having a lot of trouble reading any of the read only characteristics from this device, but I appreciate your help a lot

**Comment by hansmbakker** [comment]
@kirawadden this issue seems solved, could you please close it to keep the issue list clean?

cc @chegewara
