### ISSUE TITLE
C++ "Hello World" Project 

### ISSUE THREAD

**Issue by GarageGadget** [nkolban/esp32-snippets#6]
Hi,

I would appreciate it if you can provide the C++ configuration details e.g example "Hello World" project for C++.

This would help fast track myself and others with C++ development on the ESP32.

Keep up the good work.

BR,
Brent

**Comment by nkolban** [comment]
@GarageGadget 

Great idea ... thank you for that sir.   Here is a first pass ... have a go and lets see if this meets the need.   Please post back with comments/results.

https://github.com/nkolban/esp32-snippets/blob/master/skeletons/cpp/main_helloworld.cpp

**Comment by GarageGadget** [comment]
I replaced the main.c with main_helloworld.cpp file a project based on esp-idf-template project.

I had to add the include directory to the include path to resolve ESP_LOGD declarations. 
The code compiled and flashed without issue but unfortunately none of the application messages were sent to the uart.

A full sample project with compiler configuration etc. would help.

**Comment by nkolban** [comment]
Ahhh ... yes ... sorry ... by using ESP_LOGD() that logs at the debug level which is a lower level logging than default.  But it sounds like you got it figured.

Close this issue when you are happy.

**Comment by mumairanwar92** [comment]
@GarageGadget I'm having the same issue, will you guide me how did you adjust the log level to get the output ? Thanks in advance.
and @nkolban , Great tutorial and awesome effort writing the book about esp32. Really appreciated.

**Comment by nkolban** [comment]
@mumairanwar92 The logging is documented here ... 

http://esp-idf.readthedocs.io/en/latest/api-reference/system/log.html

At a high level, and assuming your are using ESP-IDF, run "make menuconfig" and navigate through the menus to the log settings.  Set the default log output level to debug or lower.  If you need further assistance, don't hesitate to post back.

**Comment by mumairanwar92** [comment]
@nkolban thanks for the comment. It has been resolved. you and your tutorials have been a great help throughout.

**Comment by arunbm123** [comment]
hi
I am unable to import includes file c_includes.xml.
after giving path. and finish nothing happens

**Comment by wdouglas1999** [comment]
Hi all,
I am too unable to import includes from the c_includes.xml. Exactly the same situation as arunbm123.
Has any solution been found? 
Thank you.

**Comment by chegewara** [comment]
https://github.com/nkolban/esp32-snippets/blob/master/eclipse/c_includes.xml

**Comment by burkulesomesh43** [comment]
@nkolban 
I ma using using esp idf environment on esp32 board. I want to decode url. 
URL>>file:///F:/s?ssid=cabin+336&Passkey=Cabin336%40efc

In above url, 'Cabin336%40efc' includes '%40' which has its decoded value '@'
so how to decode this?
I tried to use base64.h library file from esp idf but gives an error..
fatal error: base64.h: No such file or directory

**Comment by chegewara** [comment]
Check you esp-idf installation:
https://github.com/espressif/esp-idf/blob/master/components/wpa_supplicant/include/wpa2/utils/base64.h

**Comment by burkulesomesh43** [comment]
@chegewara 
yes, this file is on this location but when i used    #include "base64.h"  i gives error..

**Comment by chegewara** [comment]
Try like this:
https://github.com/espressif/esp-adf/blob/master/examples/cloud_services/google_translate_device/main/google_sr.c#L31

**Comment by burkulesomesh43** [comment]
@chegewara 
hey Its working.
thank you so much for help and quick response..
