### ISSUE TITLE
Random mac address error

### ISSUE THREAD

**Issue by duygudemirpence** [nkolban/esp32-snippets#623]
I want to try: BLE_client example and,
I have a this serial output:

BLE Advertised Device found: Name: , Address: 5b:db:8e:2a:25:30, manufacturer data: 060001092002580363e72e087b8df290a29359ff2e264b7af585a0072c
But the all Adress are not true. My phone address or other bluetooth device adress not include true one. How can i fix ?

**Comment by chegewara** [comment]
Are you sure that your peer devices dont use RPA mac address? Its private random mac address that is changing very often to not allow to track device.
