### ISSUE TITLE
BLE Client is not working for more than 2 characteristic.

### ISSUE THREAD

**Issue by Ananthesh015** [nkolban/esp32-snippets#629]
**Even I had name the pRemoteCharaLig it is not taking it and showing below error.**  

> Arduino: 1.8.5 (Windows 10), Board: "ESP32 Dev Module, Disabled, Default, QIO, 40MHz, 4MB (32Mb), 115200, None"
> 
> E32Client:117: error: 'pRemoteCharaLig' does not name a type
> 
>    pRemoteCharaLig= pRemoteService->getCharacteristic(charLigUUID);
> 
>    ^
> 
> E32Client:118: error: expected unqualified-id before 'if'
> 
>    if (pRemoteCharal== nullptr) {
> 
>    ^
> 
> E32Client:123: error: 'Serial' does not name a type
> 
>    Serial.println("Found Chara Lig");
> 
>    ^
> 
> E32Client:126: error: 'value' does not name a type
> 
>    value = pRemoteCharal->readValue();
> 
>    ^
> 
> E32Client:127: error: 'Serial' does not name a type
> 
>    Serial.print("The Chara value was: ");
> 
>    ^
> 
> E32Client:128: error: 'Serial' does not name a type
> 
>    Serial.println(value.c_str());
> 
>    ^
> 
> E32Client:130: error: 'pRemoteCharaLig' does not name a type
> 
>    pRemoteCharaLig->registerForNotify(notifybackLig);
> 
>    ^
> 
> E32Client:131: error: expected declaration before '}' token
> 
>  }
> 
>  ^
> 
> exit status 1
> 'pRemoteCharaLig' does not name a type
> 
> This report would have more information with
> "Show verbose output during compilation"
> option enabled in File -> Preferences.
>

**Comment by chegewara** [comment]
I dont understand one thing. In this library there is no such class or file like E32Client, but you have a lot error lines like this:
`E32Client:131:`

**Comment by hansmbakker** [comment]
@Ananthesh015 is this still an issue? If not, please close the issue to keep the issue list clean.

@chegewara

**Comment by Ananthesh015** [comment]
Hello sir, It is the name of the program that I had given to it.
