### ISSUE TITLE
compiling fails with c++ flags

### ISSUE THREAD

**Issue by wegunterjr** [nkolban/esp32-snippets#650]
`c:/users/newman/.platformio/packages/toolchain-xtensa32/bin/../lib/gcc/xtensa-esp32-elf/5.2.0/../../../../xtensa-esp32-elf/bin/ld.exe: cannot find -lCOMPONENT_NAME)`

`-DCOMPONENT_ADD_LDFLAGS= -lstdc++ -l$(COMPONENT_NAME)`

**Comment by wegunterjr** [comment]
Am i over thinking it.....
the actual c++ flag is `-lsdc++`   , but what does the second part of the line mean?
-l$(COMPONENT_NAME)  this is build system generated, so I shouldn't have to know it?  When I add it it fails and says it cannot find it... 
Can someone clarify?

**Comment by hansmbakker** [comment]
@wegunterjr can you close this issue if it is solved to keep the issue list clean?

cc @chegewara
