### ISSUE TITLE
Reading sensor values from notifycallback 

### ISSUE THREAD

**Issue by Olaclemmy** [nkolban/esp32-snippets#666]
Hi, please I am new here. I am working on BLE project using two ESP32, one as a client and the other as a server. My issue is how to read sensor values sent to the client inside notifycallback. I have been trying to work it out but with no success. 

All I want is to read sensor reading and display it on Oled LCD.

Please a quick research will be appreciated. 
Thanks.

**Comment by chegewara** [comment]
https://github.com/nkolban/esp32-snippets/blob/master/cpp_utils/tests/BLETests/SampleClient_Notify.cpp#L28-L35

**Comment by hetlelid** [comment]
Depending on your datatype, you can access the data inside the notifyCallback() function that @chegewara is referring to in the following way:

`	uint16_t wd = ((uint16_t)pData[2] << 8) | pData[1];
	float temp = wd / 100.0;`

Keep in mind this is a static function. I have tried to move all BLE code into a library for a specific device, but i struggle to update the class variables from this static function. Let me know if anyone have a clue for how to do this.

**Comment by Olaclemmy** [comment]
Thanks for your prompt feedback @chegewara, I managed to retrieve it using this method below. It might not be the best way to do it but it works. 

char rxValue[5];
For(int i = 0; i < length; i++)
{
  rxValue[i] = pData[i];
}
rxReading = (((String)rxValue).toFloat());
Serial.println(rxReading);

//Global variable 
float rxReading;

Please, I am not expert in this, but I could receive the same values I was sending from BLE server. 

If there's any improvement on this, I will really appreciate it.

**Comment by Olaclemmy** [comment]
I really appreciate your time and effort putting into your explanation, it really helps @hetlelid.

But any improvement on my method would be appreciated.

**Comment by chegewara** [comment]
Try to use this macro in notificationCallback() to output log value and paste here results:
`ESP_LOG_BUFFER_HEX("my value", pData, length);`

**Comment by Olaclemmy** [comment]
Thanks for your prompt feedback @chegewara, I will definitely do that. My appreciation.

**Comment by Olaclemmy** [comment]
Thanks for your help @chegewara, though I couldn't understand how to use what you suggested, but just putting it in my code does the job. Now I can receive true values from notificationCallback().

…..here is my code:

static void notifyCallback(
  BLERemoteCharacteristic* pBLERemoteCharacteristic,
  uint8_t* pData, size_t length, bool isNotify) 
  {
    Serial.print("Notify callback for characteristic ");
    Serial.print(pBLERemoteCharacteristic->getUUID().toString().c_str());
    ESP_LOG_BUFFER_HEX("my value", pData, length);
    Serial.print(" of data length ");
    Serial.println(length);
    Serial.print("Received Value: ");
    for (int i = 0; i <length; i++) {
       rxValue[i]= pData[i];
    Serial.print(pData[i]);
    Serial.print(" ");
   }
   fsrValue = (((String)rxValue).toFloat());
}


…..here is serial monitor output.

`BLE Advertised Device found: Name: FSR0, Address: b4:e6:2d:8d:78:b7, serviceUUID: 4fafc201-1fb5-459e-8fcc-c5c9c331914b, txPower: -21
00:41:51.490 -> haveServiceUUID: 1
00:41:51.490 -> device's UUID: 4fafc201-1fb5-459e-8fcc-c5c9c331914b
00:41:51.490 -> Found our device!  address: We are in loop.
00:41:51.490 -> We are not connected to the BLE Server yet.
00:41:51.490 -> Forming a connection to b4:e6:2d:8d:78:b7
00:41:51.490 ->  - Created client
 - Connected to server
 - Found our service
00:41:54.536 ->  - Found our characteristic
00:41:54.536 -> The characteristic value was: 0.00
00:41:54.536 -> We are now connected to the BLE Server.
Force: 0.00Kg
00:41:54.583 -> Notifications turned off
We are in loop.
00:41:56.589 -> Force: 0.00Kg
00:41:56.589 -> Notifications turned on
Notify callback for characteristic beb5483e-36e1-4688-b7f5-ea07361b26a8 of data length 4
00:41:57.692 -> Received Value: 48 46 48 48  
We are in loop.
00:41:58.593 -> Force: 0.00Kg
00:41:58.593 -> Notifications turned off
We are in loop.
00:42:00.599 -> Force: 0.00Kg
00:42:00.599 -> Notifications turned on`

**Comment by chegewara** [comment]
Looks like you have it working.

**Comment by Olaclemmy** [comment]
Yes, thanks for your help @chegewara. I will have to close this issue now,  since my problem is solved. 

Thanks once again for your time. 
Regards.
