### ISSUE TITLE
How to increase ESP32 BLE range 

### ISSUE THREAD

**Issue by Olaclemmy** [nkolban/esp32-snippets#674]
Hi everyone, please I am  developing an ESP32 BLE  for both server and client. I want to know the default distance range and possibly how to increase ESP32 BLE distance range. 

Thanks.

**Comment by chegewara** [comment]
```
esp_err_t errRc=esp_ble_tx_power_set(ESP_BLE_PWR_TYPE_DEFAULT,ESP_PWR_LVL_P9);
esp_ble_tx_power_set(ESP_BLE_PWR_TYPE_ADV, ESP_PWR_LVL_P9);
 esp_ble_tx_power_set(ESP_BLE_PWR_TYPE_SCAN ,ESP_PWR_LVL_P9); 
```
By default all three are set to `ESP_PWR_LVL_P3`, but `ESP_PWR_LVL_P9` is max possible level. Also try to avoid obstacles.

**Comment by Olaclemmy** [comment]
Thanks for your prompt feedback @chegewara, I really appreciate your time. I will give it a try and let you know my outcome.

**Comment by Olaclemmy** [comment]
Please @chegewara, what is the possible and reliable distance in meters(m) I could achieve using ESP32 BLE to BLE communication with the max transmitting power as indicated above. 
Thank you.

**Comment by chegewara** [comment]
Straight line, with no obstacles should be over 100 m.

**Comment by chegewara** [comment]
Close.

**Comment by Olaclemmy** [comment]
Thanks @chegewara

**Comment by rohitjust24idpl** [comment]
@chegewara 
I would like to decrease the radius of ESP32. 
The lowest i can get is 2m. I wanted user to get event only when he/she is standing very close to ESP32. Like below 1m.

**Comment by chegewara** [comment]
Maybe RSSI checking is an option?

**Comment by rohitjust24idpl** [comment]
Hi,
Thanks for your response.

1. RSSI checking wont give accurate results all the time i believe. 
2. And averaging out multiple values of RSSI will consume my processing time.

**My Scenario:** I am broadcasting packet only on a button press and user gets event on his/her phone.
**Expected Output:** Something like user who presses the button will receive packet and not others who are roaming nearby in 2m range. 

Any other solution to this ?

**Comment by chegewara** [comment]
I dont see an option to send advertising to only 1 device, not with current esp-idf library. Direct advertising and whitelisting is still broken.

**Comment by mptr8956** [comment]
> ```
> esp_err_t errRc=esp_ble_tx_power_set(ESP_BLE_PWR_TYPE_DEFAULT,ESP_PWR_LVL_P9);
> esp_ble_tx_power_set(ESP_BLE_PWR_TYPE_ADV, ESP_PWR_LVL_P9);
>  esp_ble_tx_power_set(ESP_BLE_PWR_TYPE_SCAN ,ESP_PWR_LVL_P9); 
> ```
> 
> By default all three are set to `ESP_PWR_LVL_P3`, but `ESP_PWR_LVL_P9` is max possible level. Also try to avoid obstacles.

hi, sorry - totally new to ESP32. I managed to flash your little program. It works but the BLE range is not really good. so i want to increase it like it is explained here. where/how do i have to execute the commands you wrote down?

**Comment by aliakbar-bsr** [comment]
Hi in which part of code we have to add these codes I mean In setup ,loop,(eth) where

**Comment by chegewara** [comment]
Somewhere after `BLEDevice::init()`, you can put in setup.
