### ISSUE TITLE
BLEUtils: enumeration value 'ESP_GATTS_SEND_SERVICE_CHANGE_EVT' not handled in switch

### ISSUE THREAD

**Issue by hetlelid** [nkolban/esp32-snippets#677]
Upgraded to latest esp-idf and arduino-esp32. Now getting the error below:

Workaround:
>        case ESP_GATTS_SEND_SERVICE_CHANGE_EVT:
>                ESP_LOGE(LOG_TAG, "ESP_GATTS_SEND_SERVICE_CHANGE_EVT not implementet");
>                return "Unknown";`

Error:
> CXX build/cpp_utils/BLEUtils.o
> /home/osboxes/esp/test/test_arduino_to_idf/components/cpp_utils/BLEUtils.cpp: In static member function 'static std::__cxx11::string BLEUtils::gattServerEventTypeToString(esp_gatts_cb_event_t)':
> /home/osboxes/esp/test/test_arduino_to_idf/components/cpp_utils/BLEUtils.cpp:988:8: error: enumeration value 'ESP_GATTS_SEND_SERVICE_CHANGE_EVT' not handled in switch [-Werror=switch]
>  switch(eventType) {

**Comment by chegewara** [comment]
Hi, 
its new event in esp-idf. This is how you can fix it:
```
	default:
		return "Unknown";
```
in this line:
https://github.com/chegewara/esp32-snippets-enchancements-test/blob/master/components/cpp_utils/BLEUtils.cpp#L1064
