### ISSUE TITLE
Every BLEDescriptor allocates 600 bytes of memory. Is this needed?

### ISSUE THREAD

**Issue by Bascy** [nkolban/esp32-snippets#683]
On construction of a BLEDescriptor, it allocates 600 bytes for m_value.
I think this is quite a lot, considering most values will be a few bytes (<20) at most in my project

Am I missing something here? 
Can I just reduce the #define used for this?

**Comment by chegewara** [comment]
@Bascy Like i answered in other topic, its not this library settings that makes descriptor 600 bytes value length. Its esp-idf bt stack.
