### ISSUE TITLE
Typo - default I2C SCL pin was DEFAULT_SDA_PIN but should have been DEFAULT_CLK_PIN

### ISSUE THREAD

**Issue by chegewara** [nkolban/esp32-snippets#70]
https://github.com/nkolban/esp32-snippets/blob/master/cpp_utils/I2C.cpp#L29

should be `DEFAULT_CLK_PIN`

**Comment by nkolban** [comment]
Thank you my friend.  That was bad :-(

The fix has been entered and committed.  MANY thanks for reporting.

**Comment by nkolban** [comment]
Closing for just now.  If needed, don't hesitate to re-open.
