### ISSUE TITLE
Documentation https://github.com/nkolban/esp32-snippets/blob/master/cpp_utils/ArduinoBLE.md

### ISSUE THREAD

**Issue by jestebanes** [nkolban/esp32-snippets#71]
Hello, Neil

in the file ArduinoBLE.md you suggest that if we want to debug an issue change the debug level modifying the line 
#define CONFIG_LOG_DEFAULT 1
from one to five in sdkconfig.h

But when I search in this file I found instead
#define CONFIG_LOG_DEFAULT_LEVEL 1

Is this the line I need to change?

Thanks for your great work, best regards

**Comment by nkolban** [comment]
Thank you sir.  I'm 99.9% you are correct.  I have updated the file to reflect the correct setting.  MANY thanks for reporting this.

**Comment by nkolban** [comment]
Closing for just now.  Don't hesitate to re-open as needed.
