### ISSUE TITLE
Should setBatteryLevel call notify?

### ISSUE THREAD

**Issue by hansmbakker** [nkolban/esp32-snippets#739]
In https://github.com/nkolban/esp32-snippets/blob/45fcc07b6d4cd65aa0ff31e3e47c9d9e458abf87/cpp_utils/BLEHIDDevice.cpp#L195-L197

Should this function call `notify` or will that broadcast a notification by itself?

**Comment by chegewara** [comment]
You should call notify, because its up to you how often you want to notify client.
I dont remember why next function is commented out, but it is not right.

**Comment by hansmbakker** [comment]
I believe that some methods were renamed (`setHidInfo` to `hidInfo` for example). Maybe you didn't want them to conflict and removed the getters?

**Comment by chegewara** [comment]
I really dont remember, but what i want to do is to create new HID library from scratch. Only i dont have time now (ble library needs to be polished) and me-no-dev wants to create own HID library, so maybe i will pass.

**Comment by chegewara** [comment]
It would be natural to add notify here:
```
void BLEHIDDevice::setBatteryLevel(uint8_t level) { 
 	m_batteryLevelCharacteristic->setValue(&level, 1); 
        m_batteryLevelCharacteristic->notify();
 } 
```

**Comment by hansmbakker** [comment]
Yes that seems logical :)

I can share my class later (I'm writing code while waiting for my dev board to arrive), also curious what the HID library from @me-no-dev would look like :)

**Comment by hansmbakker** [comment]
>           ble library needs to be polished

I'm wondering whether
- there is a list of issues or tasks for this polishing, so that it is clear for people where to help with PRs. I'm willing to send a PR for the notify change, but I'm not sure whether you have plans to change the library altogether?
- whether you can link the ESP32_BLE_Arduino and this repo so that it will take less maintenance work and less code duplication
- it is an idea to close old issues that are solved, so that it is easier to find real (open) issues?

**Comment by chegewara** [comment]
I have granted full access to this library recently and i am trying to fix issues, get control over still pending but already resolved issues, my day job and now upwork job. This is not easy. 
Anyone can make PR with changes that feels are good for this library, i will review it and merge if is needed.
I have some changes in BLEClient class but i have clean code and prepare PR. So any help is welcome and appreciated.

**Comment by hansmbakker** [comment]
I understand you have a lot of things going on, it just thought one thing might help is to create a task board at https://github.com/nkolban/esp32-snippets/projects with things people could help with.
