### ISSUE TITLE
Is BLE Security needed for BLE HID?

### ISSUE THREAD

**Issue by hansmbakker** [nkolban/esp32-snippets#741]
Looking at https://github.com/nkolban/esp32-snippets/blob/master/cpp_utils/tests/BLETests/SampleHIDDevice.cpp#L83-L84 and https://github.com/nkolban/esp32-snippets/blob/master/cpp_utils/tests/BLETests/SampleHIDDevice.cpp#L202-L205 I see that the BLE HID sample uses BLE Security.

Is this needed for BLE HID to work, or can it work together with Windows without that? I'd like to try and get a minimum sample running.

**Comment by chegewara** [comment]
Should work without security.

**Comment by hansmbakker** [comment]
Thank you!
