### ISSUE TITLE
Access Name or BLE Address in NotifyHandler

### ISSUE THREAD

**Issue by espresso-if** [nkolban/esp32-snippets#749]
Hello together,

is there a way to Access the BLEAddress inside a notify Handler for a RemoteCharacteristic?
My specific case:

Multiple devices with the same Service ID connected to clients which notifies about changes, how can I distinguish them?

I haven't found an interface to access an Attribute to accomplish this.

Plattform: ESP32 with ESP-IDF

Thank you in advance

**Comment by espresso-if** [comment]
Ok thank you
Do you know a work-around or something similar
Because I need it for an official project

**Comment by chegewara** [comment]
Except changing library code? I could not find something quick right now.

**Comment by espresso-if** [comment]
FYI

I solved it by adding the following public function to BLERemoteCharacteristic
BLEAddress  BLERemoteCharacteristic::getPeerAddress(){
	return m_pRemoteService->getClient()->getPeerAddress();
}

**Comment by chegewara** [comment]
@espresso-if Like i said, change library code. Thanks for update.

**Comment by espresso-if** [comment]
See #752
