### ISSUE TITLE
Problem using multiple characteristics

### ISSUE THREAD

**Issue by espresso-if** [nkolban/esp32-snippets#751]
Hello

I'm trying to use multiple charactericts within one service.
But when the Client retrieves the characteristics within  BLERemoteService::retrieveCharacteristics, it fails while accessing the second characteristic:
```

	if (status == ESP_GATT_INVALID_OFFSET) {   // We have reached the end of the entries.
			ESP_LOGE(LOG_TAG, "Invalid offset in status:< %s", BLEUtils::gattStatusToString(status).c_str());
			break;
		}
```
 
Output:
D (3603) BLEClient: << getService: found the service with uuid: 0855d3e4-d847-4fc5-a06d-e3ec9629146f␛[0m
D (3623) BLERemoteService: >> getCharacteristics() for service: 0855d3e4-d847-4fc5-a06d-e3ec9629146f␛[0m
D (3633) BLERemoteService: Found a characteristic: Handle: 42, UUID: c076b13d-f8b9-46e0-975a-70080fb15b09␛[0m
␛[0;31mE (3643) BLERemoteService: Invalid offset in status: Unknown␛[0m
D (3643) BLERemoteService: << getCharacteristics()␛[0m

All characteristics seemed to be added correcty at the serverside while Debugging

Thanks in advance

**Comment by chegewara** [comment]
Is this original code from this library or you added `ESP_LOGE` to have log output?
Im asking because this is code you  pionting on:
https://github.com/nkolban/esp32-snippets/blob/master/cpp_utils/BLERemoteService.cpp#L183-L185

It may be you are using old version of library or something?

**Comment by espresso-if** [comment]
There are no typos
But I think the issue is that that just one RemoteCharacteristic is found while retrieving because BLERemoteService::retrieveCharacteristics, stops after one Iteration

> if(pChar == nullptr) quit;.

 I have that in my code and that's the line where my programm stops

Only one characterstic can be found in the RemoteCharacteristic - two are missing

**Comment by chegewara** [comment]
Ok, thanks. Will check it.

**Comment by espresso-if** [comment]
Any news on this?

**Comment by chegewara** [comment]
Sorry for delay. Ive been testing it, just quick test with 2 or 3 characteristics, and i couldnt recreate it.
I have to fix one or two issues with BLEClient and update library, but still no time to do it.

**Comment by wakwak-koba** [comment]
I am fixing original bugs and succeeding multiple connections.

See below for details.
https://github.com/nkolban/esp32-snippets/issues/765#issuecomment-453900444

**Comment by wakwak-koba** [comment]
I am github-biginner so I do not know much about it, Is the procedure below?

1. create new repository. (fork from 'https://github.com/nkolban/esp32-snippets')
2. Fix code (and commit & push)
3. create Pull-Request

please tell me...

**Comment by chegewara** [comment]
Yes @wakwak-koba

**Comment by wakwak-koba** [comment]
PRed!

**Comment by HoernchenJ** [comment]
Sorry for opening this Issue again, but i am having trouble to use multiple characteristics on one service.

**Here is my example code:**

`void setup() {
  Serial.begin(115200);
  pinMode(LED_BUILTIN, OUTPUT);

  // Create the BLE Device
  BLEDevice::init("ESP32");

  // Create the BLE Server
  pServer = BLEDevice::createServer();
  pServer->setCallbacks(new ServerCallbacks());

  // Create the BLE Service
  BLEService *pService = pServer->createService(BLEUUID(SERVICE_UUID));

  // Create a Characteristic for the LED
  pLED = pService->createCharacteristic(
                      BLEUUID(LED_UUID),
                      BLECharacteristic::PROPERTY_NOTIFY |
                      BLECharacteristic::PROPERTY_READ   |
                      BLECharacteristic::PROPERTY_WRITE  
                    );
                    
  // Create a Characteristic for the pan rotation
  pPan = pService->createCharacteristic(
                      BLEUUID(PAN_UUID),
                      BLECharacteristic::PROPERTY_NOTIFY |
                      BLECharacteristic::PROPERTY_READ   |
                      BLECharacteristic::PROPERTY_WRITE  
                    );
                    
  // Create a Characteristic for the tilt rotation
  pTilt = pService->createCharacteristic(
                      BLEUUID(TILT_UUID),
                      BLECharacteristic::PROPERTY_NOTIFY |
                      BLECharacteristic::PROPERTY_READ   |
                      BLECharacteristic::PROPERTY_WRITE  
                    );

  pLED->setCallbacks(new LEDCharacteristicCallback());
  pPan->setCallbacks(new PANCharacteristicCallback());
  pTilt->setCallbacks(new TILTCharacteristicCallback());
  
  pLED->addDescriptor(new BLE2902());
  pPan->addDescriptor(new BLE2902());
  pTilt->addDescriptor(new BLE2902());

  // Start the service
  pService->start();

  // Start advertising
  pServer->getAdvertising()->start();
  Serial.println("Waiting a client connection to notify...");
}`

**This ist in the setup(). I created the UUIDs with the online generator:**
`
#define SERVICE_UUID        "4fafc201-1fb5-459e-8fcc-c5c9c331914b"
#define LED_UUID            "beb5483e-36e1-4688-b7f5-ea07361b26a8"
#define PAN_UUID            "a8d5db42-d652-422c-af30-6f61c8f9ad19"
#define TILT_UUID           "c89d5cce-14b3-4992-b8a8-234a273010c3"
`

**Problem:**
I am only able to see the pLED characteristic, the other two are missing, what am i doing wrong?
Unfortunatly there is no example code for multiple ones. 

**What i have done so far:**
I cloned this repo and build it with make and added it to the arduino IDE, so there should be the latest library.

**Comment by chegewara** [comment]
Code seems to be ok, what tool are you using to test?

**Comment by HoernchenJ** [comment]
Thanks for your quick reply.
I am using the Android App nRF Connect and just the verbose debug messages from the serial monitor in the arduino IDE.

**Comment by chegewara** [comment]
Is it possible that nRF connect remember previous data?
The thing is that android is caching services and characteristics. When you connect in top right corner you have option to refresh it.

**Comment by HoernchenJ** [comment]
Well, that fixed the problem 👍 
Thank you very much and stay healthy :D
