### ISSUE TITLE
(Waiting for toolchain fix): Arduino BLE library not working on ios

### ISSUE THREAD

**Issue by ahachicha** [nkolban/esp32-snippets#76]
Hello Kolban,
it's not working on mac ios. i get this errors:

*Editor*: Move to Pastebin: https://pastebin.com/7GgVrNmu

I have the last version from Arduino and from the library

**Comment by nkolban** [comment]
Howdy,
The good news is that we have seen this problem before ... can I ask you to look at this issue and resolution:

https://github.com/nkolban/esp32-snippets/issues/59

Can you upgrade your Arduino ESP32 base within your Arduino IDE and test again.  Hopefully that will resolve the problem ... but either way, hoping to hear back from you.

**Comment by pdxalz** [comment]
I am also unable to get the BLE lib to work.  I've tried both Windows 10 and Ubuntu.  Everything was installed fresh today.  Arduino version 1.8.4.  I am able to run the wifi scan app just fine on the esp32.  
I get build errors when I build the BLE_Client app (same on windows and ubuntu): [https://pastebin.com/hQ7JDxXp](url)

On Windows I used the library manager and found version 0.4.2 (I tried all of them with the same result)
On Ubuntu I built the .zip file and used the install zip feature.

Alan

**Comment by nkolban** [comment]
@pdxalz 
See issue #82 

The latest ESP-IDF has introduced a breaking change to the APIs used by the BLE C++ classes.  This is being addressed and tracked as #82.

**Comment by nkolban** [comment]
The great news is that the Arduino ESP32 project has been updated.  Please re-build your base Arduino ESP32 environment.  The even better news is that the owner of that project has decided to include the BLE C++ classes as part of the distribution.  So it is now baked in.  Please re-test and let us now see where we stand.

**Comment by nkolban** [comment]
Closing for just now.  Re-open as needed.
