### ISSUE TITLE
ESP32 does not boot with external power after BLEDevice::init

### ISSUE THREAD

**Issue by naaaas** [nkolban/esp32-snippets#785]
HI.
 i'm newbie with esp32. I designed a simple BLE scanner wichs works fine when connected to usb. The problem is that if i disconnect board from usb and connect it to power (5v) device does not boot. Just red led is On and even if i push boot or en buttons...it never boot again. Any ideas?

Thank you

**Comment by chegewara** [comment]
Find better power source? This one may be not suficient.

**Comment by naaaas** [comment]
I tried a lot of things. Even board samomes like "wifi scanner" and happends the same. But what do you mean with...better power source?

**Comment by chegewara** [comment]
https://github.com/nkolban/esp32-snippets/issues/168

try to search `esp32 brownout`

**Comment by mitchjs** [comment]
Try this:

 

//////////////////////////////////////////////////////////

    // DISABLE BROWNOUT DETECTOR (BT Radio power up would trigger under USB power only)

    //////////////////////////////////////////////////////////

    REG_CLR_BIT(RTC_CNTL_BROWN_OUT_REG, RTC_CNTL_BROWN_OUT_ENA);

 

    //////////////////////////////////////////////////////////

            // SET UP BLE

            //////////////////////////////////////////////////////////

            // create BLE service

            BLEDevice::init(MODEL);

            

 

    //////////////////////////////////////////////////////////

    // ENABLE BROWNOUT DETECTOR

    //////////////////////////////////////////////////////////

    REG_SET_BIT(RTC_CNTL_BROWN_OUT_REG, RTC_CNTL_BROWN_OUT_ENA);

 

 

I have a Switching supply that supplies 300ma, and when the radio intiailizes

It doesn’t draw more that 300ma, but it spikes, and maybe the “smart” switching supply

LM2841Y, detects it and stops its output

 

 

mitch

**Comment by naaaas** [comment]
thank you but...still wrong.  this time red light is very very low when connecting to VIN. im quite lost

**Comment by PyTechMike** [comment]
Hi! Have the same issue. I use Arduino IDE, if it matters. Could you please help me a bit, don't really understood the solution. Thanks!

**Comment by chegewara** [comment]
https://www.google.com/search?q=esp32+brownout&oq=esp32+brownout&aqs=chrome..69i57.14248j0j1&sourceid=chrome&ie=UTF-8
