### ISSUE TITLE
unable to Add Whitelist

### ISSUE THREAD

**Issue by onesbasket** [nkolban/esp32-snippets#817]
I try to add whitelist, But It seemed not working...
I am happy to hear some advise.

Attaching code is copy from BLE_server_multiconnec.ino And debug log of Arudino IDE.

```
#include <BLEDevice.h>
#include <BLEServer.h>
#include <BLEUtils.h>
#include <BLE2902.h>

BLEServer* pServer = NULL;
BLECharacteristic* pCharacteristic = NULL;
bool deviceConnected = false;
bool oldDeviceConnected = false;
uint32_t value = 0;

// See the following for generating UUIDs:
// https://www.uuidgenerator.net/

#define SERVICE_UUID        "4fafc201-1fb5-459e-8fcc-c5c9c331914b"
#define CHARACTERISTIC_UUID "beb5483e-36e1-4688-b7f5-ea07361b26a8"


class MyServerCallbacks: public BLEServerCallbacks {
    void onConnect(BLEServer* pServer) {
      deviceConnected = true;
      BLEDevice::startAdvertising();
    };

    void onDisconnect(BLEServer* pServer) {
      deviceConnected = false;
    }
};





class MyCallbacks: public BLECharacteristicCallbacks {
  void onWrite(BLECharacteristic *pCharacteristic) {
    std::string value = pCharacteristic->getValue();
    String strValue = "";

    
    if (value.length() > 0) {
      Serial.println("*********");
      Serial.print("New value: ");
      for (int i = 0; i < value.length(); i++) {
        Serial.print(value[i]);
        strValue += value[i];
      }
      Serial.println();
      Serial.println("*********");
    }
  }
};


void setup() {
  Serial.begin(115200);

  // Create the BLE Device
  BLEDevice::init("ESP32");

  // Create the BLE Server
  pServer = BLEDevice::createServer();
  pServer->setCallbacks(new MyServerCallbacks());

  // Create the BLE Service
  BLEService *pService = pServer->createService(SERVICE_UUID);

  // Create a BLE Characteristic
  pCharacteristic = pService->createCharacteristic(
                      CHARACTERISTIC_UUID,
                      BLECharacteristic::PROPERTY_READ   |
                      BLECharacteristic::PROPERTY_WRITE  |
                      BLECharacteristic::PROPERTY_NOTIFY |
                      BLECharacteristic::PROPERTY_INDICATE
                    );

  pCharacteristic->setCallbacks(new MyCallbacks());

  // https://www.bluetooth.com/specifications/gatt/viewer?attributeXmlFile=org.bluetooth.descriptor.gatt.client_characteristic_configuration.xml
  // Create a BLE Descriptor
  pCharacteristic->addDescriptor(new BLE2902());

  // Start the service
  pService->start();

  // Start advertising
  BLEAdvertising *pAdvertising = BLEDevice::getAdvertising();
  pAdvertising->addServiceUUID(SERVICE_UUID);
  pAdvertising->setScanResponse(false);
  uint8_t mac[] = {0x9c, 0x5c, 0xf9, 0xf2, 0xaa, 0xf0};
  BLEDevice::whiteListAdd(mac);
  pAdvertising->setScanFilter(false,true);
  pAdvertising->setMinPreferred(0x0);  // set value to 0x00 to not advertise this parameter
  BLEDevice::startAdvertising();
  Serial.println("Waiting a client connection to notify...");
}

void loop() {
    // notify changed value
    if (deviceConnected) {
        pCharacteristic->setValue((uint8_t*)&value, 4);
        pCharacteristic->notify();
        value++;
        delay(1000); // bluetooth stack will go into congestion, if too many packets are sent, in 6 hours test i was able to go as low as 3ms
    }
    // disconnecting
    if (!deviceConnected && oldDeviceConnected) {
        delay(500); // give the bluetooth stack the chance to get things ready
        pServer->startAdvertising(); // restart advertising
        Serial.println("start advertising");
        oldDeviceConnected = deviceConnected;
    }
    // connecting
    if (deviceConnected && !oldDeviceConnected) {
        // do stuff here on connecting
        oldDeviceConnected = deviceConnected;
    }
}
```

> [D][BLEDevice.cpp:82] createServer(): >> createServer
[D][BLEServer.cpp:290] registerApp(): >> registerApp - 0
[D][FreeRTOS.cpp:165] take(): Semaphore taking: name: RegisterAppEvt (0x3ffdee48), owner: <N/A> for registerApp
[D][FreeRTOS.cpp:174] take(): Semaphore taken:  name: RegisterAppEvt (0x3ffdee48), owner: registerApp
[D][BLEDevice.cpp:108] gattServerEventHandler(): gattServerEventHandler [esp_gatt_if: 4] ... Unknown
[D][BLEServer.cpp:153] handleGATTServerEvent(): >> handleGATTServerEvent: Unknown
[D][BLEServer.cpp:294] registerApp(): << registerApp
[D][BLEServer.cpp:280] handleGATTServerEvent(): << handleGATTServerEvent
[D][BLEDevice.cpp:89] createServer(): << createServer
[D][BLEServer.cpp:76] createService(): >> createService - 4fafc201-1fb5-459e-8fcc-c5c9c331914b
[D][FreeRTOS.cpp:165] take(): Semaphore taking: name: CreateEvt (0x3ffdf0a0), owner: <N/A> for createService
[D][FreeRTOS.cpp:174] take(): Semaphore taken:  name: CreateEvt (0x3ffdf0a0), owner: createService
[D][BLEService.cpp:67] executeCreate(): >> executeCreate() - Creating service (esp_ble_gatts_create_service) service uuid: 4fafc201-1fb5-459e-8fcc-c5c9c331914b
[D][FreeRTOS.cpp:165] take(): Semaphore taking: name: CreateEvt (0x3ffdf364), owner: <N/A> for executeCreate
[D][FreeRTOS.cpp:174] take(): Semaphore taken:  name: CreateEvt (0x3ffdf364), owner: executeCreate
[D][BLEDevice.cpp:108] gattServerEventHandler(): gattServerEventHandler [esp_gatt_if: 4] ... Unknown
[D][BLEServer.cpp:153] handleGATTServerEvent(): >> handleGATTServerEvent: Unknown
[D][BLEService.cpp:201] setHandle(): >> setHandle - Handle=0x28, service UUID=4fafc201-1fb5-459e-8fcc-c5c9c331914b)
[D][BLEService.cpp:207] setHandle(): << setHandle
[D][BLEService.cpp:83] executeCreate(): << executeCreate
[D][BLEServer.cpp:280] handleGATTServerEvent(): << handleGATTServerEvent
[D][BLEServer.cpp:92] createService(): << createService
[D][BLEService.cpp:229] addCharacteristic(): >> addCharacteristic()
[D][BLEService.cpp:232] addCharacteristic(): Adding characteristic: uuid=beb5483e-36e1-4688-b7f5-ea07361b26a8 to service: UUID: 4fafc201-1fb5-459e-8fcc-c5c9c331914b, handle: 0x28
[D][BLEService.cpp:244] addCharacteristic(): << addCharacteristic()
[D][BLECharacteristic.cpp:559] setCallbacks(): >> setCallbacks: 0x3ffdf1c0
[D][BLECharacteristic.cpp:561] setCallbacks(): << setCallbacks
[D][BLECharacteristic.cpp:73] addDescriptor(): >> addDescriptor(): Adding UUID: 00002902-0000-1000-8000-00805f9b34fb, handle: 0xffff to UUID: beb5483e-36e1-4688-b7f5-ea07361b26a8, handle: 0xffff Read Write Notify Indicate 
[D][BLECharacteristic.cpp:75] addDescriptor(): << addDescriptor()
[D][BLEService.cpp:141] start(): >> start(): Starting service (esp_ble_gatts_start_service): UUID: 4fafc201-1fb5-459e-8fcc-c5c9c331914b, handle: 0x28
[D][BLECharacteristic.cpp:84] executeCreate(): >> executeCreate()
[D][BLECharacteristic.cpp:95] executeCreate(): Registering characteristic (esp_ble_gatts_add_char): uuid: beb5483e-36e1-4688-b7f5-ea07361b26a8, service: UUID: 4fafc201-1fb5-459e-8fcc-c5c9c331914b, handle: 0x28
[D][FreeRTOS.cpp:165] take(): Semaphore taking: name: CreateEvt (0x3ffdf910), owner: <N/A> for executeCreate
[D][FreeRTOS.cpp:174] take(): Semaphore taken:  name: CreateEvt (0x3ffdf910), owner: executeCreate
[D][BLEDevice.cpp:108] gattServerEventHandler(): gattServerEventHandler [esp_gatt_if: 4] ... Unknown
[D][BLEServer.cpp:153] handleGATTServerEvent(): >> handleGATTServerEvent: Unknown
[D][BLECharacteristic.cpp:576] setHandle(): >> setHandle: handle=0x2a, characteristic uuid=beb5483e-36e1-4688-b7f5-ea07361b26a8
[D][BLECharacteristic.cpp:578] setHandle(): << setHandle
[D][BLECharacteristic.cpp:203] handleGATTServerEvent(): >> handleGATTServerEvent: Unknown
[D][BLECharacteristic.cpp:459] handleGATTServerEvent(): << handleGATTServerEvent
[D][BLEDescriptor.cpp:66] executeCreate(): >> executeCreate(): UUID: 00002902-0000-1000-8000-00805f9b34fb, handle: 0xffff
[D][BLEServer.cpp:280] handleGATTServerEvent(): << handleGATTServerEvent
[D][FreeRTOS.cpp:165] take(): Semaphore taking: name: CreateEvt (0x3ffdfa0c), owner: <N/A> for executeCreate
[D][FreeRTOS.cpp:174] take(): Semaphore taken:  name: CreateEvt (0x3ffdfa0c), owner: executeCreate
[D][BLEDevice.cpp:108] gattServerEventHandler(): gattServerEventHandler [esp_gatt_if: 4] ... Unknown
[D][BLEServer.cpp:153] handleGATTServerEvent(): >> handleGATTServerEvent: Unknown
[D][BLECharacteristic.cpp:203] handleGATTServerEvent(): >> handleGATTServerEvent: Unknown
[D][BLEDescriptor.cpp:229] setHandle(): >> setHandle(0x2b): Setting descriptor handle to be 0x2b
[D][BLEDescriptor.cpp:231] setHandle(): << setHandle()
[D][BLEDescriptor.cpp:90] executeCreate(): << executeCreate
[D][BLECharacteristic.cpp:459] handleGATTServerEvent(): << handleGATTServerEvent
[D][BLECharacteristic.cpp:121] executeCreate(): << executeCreate
[D][BLEServer.cpp:280] handleGATTServerEvent(): << handleGATTServerEvent
[D][FreeRTOS.cpp:165] take(): Semaphore taking: name: StartEvt (0x3ffdf424), owner: <N/A> for start
[D][FreeRTOS.cpp:174] take(): Semaphore taken:  name: StartEvt (0x3ffdf424), owner: start
[D][BLEDevice.cpp:108] gattServerEventHandler(): gattServerEventHandler [esp_gatt_if: 4] ... Unknown
[D][BLEServer.cpp:153] handleGATTServerEvent(): >> handleGATTServerEvent: Unknown
[D][BLEService.cpp:166] start(): << start()
[D][BLECharacteristic.cpp:203] handleGATTServerEvent(): >> handleGATTServerEvent: Unknown
[I][BLEDevice.cpp:561] getAdvertising(): create advertising
[D][BLECharacteristic.cpp:459] handleGATTServerEvent(): << handleGATTServerEvent
[D][BLEDevice.cpp:563] getAdvertising(): get advertising
[D][BLEServer.cpp:280] handleGATTServerEvent(): << handleGATTServerEvent
[D][BLEDevice.cpp:493] whiteListAdd(): >> whiteListAdd: 9c:5c:f9:f2:aa:f0
[D][BLEDevice.cpp:498] whiteListAdd(): << et advertising[D][BLEDevice.cpp:563] getAdvertising(): get advertising
[D][BLEAdvertising.cpp:123] setScanFilter(): >> setScanFilter: scanRequestWhitelistOnly: 0, connectWhitelistOnly: 1
[D][BLEAdvertising.cpp:479] handleGAPEvent(): handleGAPEvent [event no: 27]
[D][BLEAdvertising.cpp:136] setScanFilter(): << setScanFilter
[D][BLEDevice.cpp:568] startAdvertising(): >> startAdvertising
[D][BLEDevice.cpp:563] getAdvertising(): get advertising
[D][BLEAdvertising.cpp:186] start(): >> start: customAdvData: 0, customScanResponseData: 0
[D][BLEAdvertising.cpp:198] start(): - advertising service: 4fafc201-1fb5-459e-8fcc-c5c9c331914b
[D][BLEAdvertising.cpp:246] start(): << startad[D][BLEDevice.cpp:563] getAdvertising(): get advertising
[D][BLEDevice.cpp:570] startAdvertising(): << startAdvertising
[D][BLEAdvertising.cpp:479] handleGAPEvent(): handleGAPEvent [event no: 0]
[D][BLEDevice.cpp:563] getAdvertising(): get advertising
[D][BLEAdvertising.cpp:479] handleGAPEvent(): handleGAPEvent [event no: 6]

**Comment by suleatac** [comment]
hello @onesbasket ,
did you solve this problem ? how did you solve? can you explain to me? I am trying to use white list in my code, too
