### ISSUE TITLE
max # of characteristics supported?

### ISSUE THREAD

**Issue by hellowtisch** [nkolban/esp32-snippets#829]
I have set up a BLE service and added 6 characteristics.
Any BLE client I used only finds 5 of the characteristics. The last one is always not found.
I changed the sequence of characteristics added and still, the last one added is not found.

Is there a limit on max # of characteristics supported per service on a esp32?

Here is my server code snippet:

`
#define SERVICE_UUID        "4fafc201-1fb5-459e-8fcc-c5c9c331914b"
#define CHARACTERISTIC_UUID "beb5483e-36e1-4688-b7f5-ea07361b26a0"
#define CHARACTERISTIC1_UUID "beb5483e-36e1-4688-b7f5-ea07361b26a1"
#define CHARACTERISTIC2_UUID "beb5483e-36e1-4688-b7f5-ea07361b26a2"
#define CHARACTERISTIC3_UUID "beb5483e-36e1-4688-b7f5-ea07361b26a3"
#define CHARACTERISTIC4_UUID "beb5483e-36e1-4688-b7f5-ea07361b26a4"
#define CHARACTERISTIC5_UUID "beb5483e-36e1-4688-b7f5-ea07361b26a5"

BLECharacteristic *pCharacteristic;
BLECharacteristic *pCharacteristic1;
BLECharacteristic *pCharacteristic2;
BLECharacteristic *pCharacteristic3;
BLECharacteristic *pCharacteristic4;
BLECharacteristic *pCharacteristic5;

BLEDevice::init("Sensor Testserver");
  BLEServer *pServer = BLEDevice::createServer();
  pServer->setCallbacks(new MyServerCallbacks());

  BLEService *pService = pServer->createService(SERVICE_UUID);
  pCharacteristic = pService->createCharacteristic(
                                         CHARACTERISTIC_UUID,
                                         BLECharacteristic::PROPERTY_READ |
                                         BLECharacteristic::PROPERTY_NOTIFY 
                                       );
 pCharacteristic1 = pService->createCharacteristic(
                                         CHARACTERISTIC1_UUID,
                                         BLECharacteristic::PROPERTY_READ |
                                         BLECharacteristic::PROPERTY_NOTIFY 
                                       );
 pCharacteristic2 = pService->createCharacteristic(
                                         CHARACTERISTIC2_UUID,
                                         BLECharacteristic::PROPERTY_READ |
                                         BLECharacteristic::PROPERTY_NOTIFY 
                                       );
                                       
 pCharacteristic3 = pService->createCharacteristic(
                                         CHARACTERISTIC3_UUID,
                                         BLECharacteristic::PROPERTY_READ |
                                         BLECharacteristic::PROPERTY_NOTIFY 
                                       );
                                       
 pCharacteristic4 = pService->createCharacteristic(
                                         CHARACTERISTIC4_UUID,
                                         BLECharacteristic::PROPERTY_READ |
                                         BLECharacteristic::PROPERTY_NOTIFY 
                                       );  
 
                                        
 pCharacteristic5 = pService->createCharacteristic(
                                         CHARACTERISTIC5_UUID,
                                         BLECharacteristic::PROPERTY_READ |
                                         BLECharacteristic::PROPERTY_NOTIFY 
                                       );                    

pCharacteristic->setValue("Pitch");
  pCharacteristic->addDescriptor(new BLE2902());
  pCharacteristic1->setValue("Roll");
  pCharacteristic1->addDescriptor(new BLE2902());
  pCharacteristic2->setValue("Heading");
  pCharacteristic2->addDescriptor(new BLE2902());
  pCharacteristic3->setValue("Pitch");
  pCharacteristic3->addDescriptor(new BLE2902());
  pCharacteristic4->setValue("Roll");
  pCharacteristic4->addDescriptor(new BLE2902());
  pCharacteristic5->setValue("Heading");
  pCharacteristic5->addDescriptor(new BLE2902());

pService->start();
  // BLEAdvertising *pAdvertising = pServer->getAdvertising();  // this still is working for backward compatibility
  BLEAdvertising *pAdvertising = BLEDevice::getAdvertising();
  pAdvertising->addServiceUUID(SERVICE_UUID);
  pAdvertising->setScanResponse(true);
  pAdvertising->setMinPreferred(0x06);  // functions that help with iPhone connections issue
  pAdvertising->setMinPreferred(0x12);
  BLEDevice::startAdvertising();                                                 
`

**Comment by hellowtisch** [comment]
in addition, I have another strange observation:
for characteristics 0-3 I do get notifications, with characteristic 4 however, notifications do not work. It is possible to read the values, but changes do not get pushed. So this seems a strange behavior.
Could this be due to performance constraints on the ESP32?

**Comment by chegewara** [comment]
numHandles:
https://github.com/nkolban/esp32-snippets/blob/master/cpp_utils/BLEServer.h#L67

**Comment by hellowtisch** [comment]
that works! 
@chegewara thank you very much!

**Comment by oliwilson** [comment]
> that works!
> @chegewara thank you very much!

Could you possibly share the line of code you implemented to fix this issue? I have the exact same issue and am struggling to implement numHandles to resolve it without syntax errors.

**Comment by hellowtisch** [comment]
here's the line of code that worked for me:
BLEService *pService = pServer->createService(BLEUUID(SERVICE_UUID), 30, 0);

Cheers

**Comment by MohammedYusufMitha** [comment]
> here's the line of code that worked for me:
> BLEService *pService = pServer->createService(BLEUUID(SERVICE_UUID), 30, 0);
> 
> Cheers

I was facing the same issue, this resolved it, thanks a lot!!!

**Comment by Sladerix** [comment]
I found a way that helps me to find the correct numHandles value. Is this making any sense?

`numHandles = (# of Characteristics)*2  +  (# of Services) + (# of Characteristics with BLE2902)`

the # of Characteristics is multiplied by 2 because of Reading Channel and Writing Channel (I supposed)

**Comment by chegewara** [comment]
Yes, that seems to be correct, more or less.

**Comment by Axliyor** [comment]
@chegewara thanks!!!

**Comment by WelliSolutions** [comment]
The method is called `createService()`. Why should I add up the number of services then? What do the other services have to do with the service I am just creating?

**Comment by chegewara** [comment]
Its not number of services. It is a number of handles reserved in service.
Each characteristic and descriptor requires some handles and also is occupying some memory, thus arbitrary default value.
If your setup requires more handles, because you are using a lot of characteristics and/or descriptors then you can use this param.

**Comment by WelliSolutions** [comment]
So the [formula](https://github.com/nkolban/esp32-snippets/issues/829#issuecomment-963393585)
```cpp
numHandles = (# of Characteristics)*2  +  (# of Services) + (# of Characteristics with BLE2902)
```
should not include `(# of Services)`.

**Comment by chegewara** [comment]
Probably yes.
Like i said, it is more or less correct formula. As you can see this formula does not include descriptors other than 2902.

You have 2 options:
- experiment with code and see how many handles you really need
- make some assumption and set higher value you need, it wont hurt too much in meaning of memory usage

**Comment by pablonunez** [comment]
As I have checked:
numHandles = (# of Services) + (# of descriptors in characteristics) + (# of properties in characteristics)

**Comment by PhLuReh** [comment]
Nice, that I finally found this solution here. But I don't know, why the API is not raising runtime errors (return values) or at least log outputs, which would make the behavior more predictable. I stumbled upon the issue while adding more characteristics and noticing that previously working functionality got lost again - or even LoadProhibited exceptions.

I would consider reopening this issue.
