### ISSUE TITLE
Can the server get the rssi of the connected client?

### ISSUE THREAD

**Issue by Wyctus** [nkolban/esp32-snippets#852]
I would like to know how far is the client which tries to connect to the server. 
That's why I planning to approximate it based on the rssi. 
I spent hours looking for such function in the esp-idf, but can't really find it.

In the ```onConnect(BLEServer* pServer, esp_ble_gatts_cb_param_t* param)``` function I found the client address in the ```param``` and seems like the ```esp_ble_gap_read_rssi(esp_bd_addr_t remote_addr)``` can help me, but I'm stucked since it doesn't return the rssi, only a status message.
How can I get the rssi value?

Thanks in advance!

**Comment by chegewara** [comment]
Hi,
yes, there is no implemented in BLEServer function to read RSSI, but you can use method you described. What you will need to add is custom gap handler and in that handler you will need to catch rssi read event.

**Comment by Wyctus** [comment]
Thank you, works fine!

**Comment by Consistometru** [comment]
Hi,
Is there an example of this function for Arduino IDE? I'm having a hard time translating from ESP-IDF

**Comment by chegewara** [comment]
https://github.com/nkolban/esp32-snippets/blob/master/cpp_utils/BLEClient.cpp#L366
