### ISSUE TITLE
Enumerating service maps

### ISSUE THREAD

**Issue by davejel** [nkolban/esp32-snippets#917]
hi all
firstly a BIG thank you to Nick Kolban for his BLE library, i am learning so much about not justBLE but programming in general by using it.
after reading #339 i decided to 'have a go' for myself and dont quite understand the results.
I have one server and one client device
once the client connects to the server i used :
    auto servicesMap = pClient->getServices();   // got services map   how to use
    // show content:
    std::map<std::string, BLERemoteService*>::iterator itr;
    Serial.println("----- Service Map: -----");
    for(itr=servicesMap->begin(); itr!=servicesMap->end(); itr++) {
      cout << '\t' << itr->first << '\t' << itr->second << '\n';
    }
to print the map (after using some extra libs with Arduino)
the results from this are:
----- Service Map: -----
	00001800-0000-1000-8000-00805f9b34fb	0x3ffe09a0
	00001801-0000-1000-8000-00805f9b34fb	0x3ffe087c
	18736d62-048b-47e8-8b37-02ec4c3e5f7c	0x3ffe0a94

the third entry is the UUID of my server Service but the other two i have no idea about, can anyone explain the output in a bit more detail please
thanks in advance

Dave

**Comment by chegewara** [comment]
```
00001800-0000-1000-8000-00805f9b34fb 0x3ffe09a0
00001801-0000-1000-8000-00805f9b34fb 0x3ffe087c
```
Those 2 are standard bluetooth services that every BLE device is obligated to have.
https://www.bluetooth.com/specifications/gatt/services/

**Comment by davejel** [comment]
@chegewara 
thank you, also for the link
Dave
