### ISSUE TITLE
i need some help really fast

### ISSUE THREAD

**Issue by NikisCodes** [nkolban/esp32-snippets#921]
example file i used

CameraWebServer.ino

Arduino: 1.8.10 (Windows 10), Board: "ESP32 Wrover Module, Huge APP (3MB No OTA/1MB SPIFFS), QIO, 80MHz, 921600

esptool.py v2.6
Serial port COM6
Connecting....
Chip is ESP32D0WDQ6 (revision 1)
Features: WiFi, BT, Dual Core, 240MHz, VRef calibration in efuse, Coding Scheme None
MAC: 24:6f:28:2a:44:8c
Uploading stub...
Running stub...
Stub running...
Changing baud rate to 921600
Changed.
Configuring flash size...
Auto-detected Flash size: 4MB
Compressed 8192 bytes to 47...

Writing at 0x0000e000... (100 %)
Wrote 8192 bytes (47 compressed) at 0x0000e000 in 0.0 seconds (effective 4096.1 kbit/s)...

A fatal error occurred: Timed out waiting for packet header
A fatal error occurred: Timed out waiting for packet header

**Comment by chegewara** [comment]
Really fast answer here, you have problem with flashing board. Use google, there is literally hundreds similar issue and answers how to solve it.

**Comment by NikisCodes** [comment]
i know to use google, after 8 hours of searching many issue sound similar i tried them all but none of them seemed to fix my problem so now i turn up to stackoverflow and github for answers when i check my serial monitor and reset pins it states waiting foe download when i start upload it connects to board as well but then this error happens each f time i already tried 5v connection external 
power  connections nothings seems to work

**Comment by NikisCodes** [comment]
@chegewara  thanks for replying i have seen your replies in other similar issueses too seems like you are really helpfull and active
