### ISSUE TITLE
BLEScan Discovering device only on first call of start

### ISSUE THREAD

**Issue by CPZbre** [nkolban/esp32-snippets#93]
The scan result history is not cleared on each start.

In BLEScan::start at  line 208 replace
`m_scanResults.m_vectorAdvertisedDevices.empty();`
by
`m_scanResults.m_vectorAdvertisedDevices.clear();`

**Comment by nkolban** [comment]
Awesome catch.  Thank you kind sir.  Changes made with my gratitude.
