### ISSUE TITLE
no matching function for call to 'BLEClient::getService()'

### ISSUE THREAD

**Issue by yeshpi** [nkolban/esp32-snippets#934]
hi, i am tried to Get a map of the services offered by the remote BLE Server
and i used BLE_Client.io changed this diclaration "BLERemoteService* pRemoteService = pClient->getService(serviceUUID); " to this "std::map<std::string, BLERemoteService*>* test=pClient->getService();" and i got this error " no matching function for call to 'BLEClient::getService()'"
please help.

**Comment by chegewara** [comment]
You have to add UUID parameter, there is no function getService() with 0 parameters.
Maybe you want to use `getServices()`?

**Comment by yeshpi** [comment]
thanks you are write i, missed "s" that's why .
