### ISSUE TITLE
getName() BLE ESP32 Library return alway NULL!

### ISSUE THREAD

**Issue by Pietro1994** [nkolban/esp32-snippets#967]
When I call the `getName()` function it returns the device name only of the very first scan, while in the subsequent NULL. Why?

this is the code:

`
void scanArea()
{
  BLEScan* pBLEScan;
  Serial.print("\n#############################################################");
  Serial.print("\n###### My Address MAC BLE: ");
  Serial.print(MyMAC);
  Serial.print("\n#############################################################");
  pBLEScan = BLEDevice::getScan();
  pBLEScan->setActiveScan(true);  
  BLEScanResults results = pBLEScan->start(1); 
  Serial.println("\n-----------------------------Device--------------------------------");

  for (int i = 0; i < results.getCount(); i++) 
  {
    Serial.println("\n_______________________________________________________________________");
    BLEAdvertisedDevice device = results.getDevice(i);
    Serial.print("\nDevice Address ");
    Serial.print(i + 1);
    Serial.print(": ");
    MAC = device.getAddress().toString().c_str();
    Serial.print(MAC);
    Serial.print(" | Rssi: ");
    Rssi_device = device.getRSSI();
    Serial.print(Rssi_device);
    Name = device.getName().c_str();
    Serial.print(" | Nome Device: ");
    Serial.print(Name);
    Manufacturer = device.getManufacturerData().c_str();
    Serial.print(" | Manufacturer Device: ");
    Serial.print(Manufacturer);
  }
  Serial.print("\n__________________________________________________________________________");
}
`

And this is code to Init BLE:

`
#define SERVICE_UUID "6E400001-B5A3-F393-E0A9-E50E24DCCA9E"
#define CHARACTERISTIC_UUID_RX "6E400001-B5A3-F393-E0A9-E50E24DCCA9E"
#define CHARACTERISTIC_UUID_TX "6E400001-B5A3-F393-E0A9-E50E24DCCA9E"
BLECharacteristic *pCharacteristic;
BLEServer *pServer;
BLEService *pService;

void enableBLE()
{
  BLEAdvertisementData pAdvertisementData;
  BLEDevice::init("Bubble"); 
  pServer = BLEDevice::createServer();
  pService = pServer->createService(SERVICE_UUID);
  pCharacteristic = pService->createCharacteristic(
                      CHARACTERISTIC_UUID_TX,
                      BLECharacteristic::PROPERTY_NOTIFY
                      );
  pAdvertisementData.setName("Bubble");
  pAdvertisementData.setManufacturerData("Bubble");
  pService->start();
  pServer->getAdvertising()->start();
  BLEAddress  ADD = BLEDevice::getAddress();
  MyMAC = ADD.toString().c_str();
  Serial.print("\n\nMy Address:");
  Serial.print(MyMAC);
  Serial.print("\n------------------------------------------------");
}
`

what can I do to have the name of the device at each scan?

thanks.

**Comment by chegewara** [comment]
Use this example as reference, especially this line:
https://github.com/espressif/arduino-esp32/blob/master/libraries/BLE/examples/BLE_server/BLE_server.ino#L35

**Comment by Pietro1994** [comment]
My ESP32 when scanning the area only finds the name in the first scan and the subsequent NULL. But thanks to your answer I managed to consider another parameter that was able to help me in my work. Thanks for your answer.
However the `getName()` has some problems, because I have seen that other people have the same problem.

**Comment by chegewara** [comment]
Yes, i seen many similar issues opened and always it was users fault. I could always deliver logs that shows i can scan how many times i want with device name in result every single time.

**Comment by Pietro1994** [comment]
Thanks for the time you have dedicated to me, because thanks to you I found another way that led me to the goal.
However the problem of `getName()` from things is due?
Why so many people have had this problem but nobody has managed to find a solution.

**Comment by chegewara** [comment]
If you could use nRF connect as a tool to scan and see what data is advertised in peripheral that you want to scan with name, which esp32 dont want to scan with name then we could try to find why. When you find that peripheral is really advertising name you can copy raw data or paste screenshot and i will try to find reason.
