### ISSUE TITLE
How can I fetch battery voltage?from servicedatauuid or payload?

### ISSUE THREAD

**Issue by masdel123** [nkolban/esp32-snippets#991]
I use eddystone tlm to fetch battery voltage.

but I cannot understand that can I fetch this battery voltage from servicedatauuid or payload. if payload.how can I encode this data to receive battery voltage?

**Comment by chegewara** [comment]
https://github.com/espressif/arduino-esp32/issues/3833

**Comment by masdel123** [comment]
thank you.I solved my problem
