### ISSUE TITLE
Try to read characteristic value but nothing Show up

### ISSUE THREAD

**Issue by greatwuu** [nkolban/esp32-snippets#999]
Hi, I'm a newbie to ble. I try to read a value from the characteristic UUID like battery level, device name and current time. By far 
device name can be read easily without any problem but other goes south with current time and battery level the output from serial monitor look like those value can be read but nothing shows up. But I can read those values when use another phone with nRF Connect to read it, Did I need to pair with passcode before read those values??. Below is my code modified from the 

https://paste.ofcode.org/ebwGi5T9p6rm6x7urcveGK

![image](https://user-images.githubusercontent.com/69145075/89169776-e3b91100-d5a8-11ea-8520-7dd9f6d12207.png)

**Comment by chegewara** [comment]
You are trying to print string, but the value is most likely not string:
`Serial.println(value.c_str());`

**Comment by greatwuu** [comment]
Oh! Thank you, I'll try to find ways to prints the hex value

**Comment by greatwuu** [comment]
> You are trying to print string, but the value is most likely not string:
> `Serial.println(value.c_str());`

Or this library is on development for reading hex/binary from characteristic I do some research on these issues repo and found this [https://github.com/nkolban/esp32-snippets/issues/596#issue-339059560](url) . And I still don't know how to print those values out. By far I've read and research for readValue() function it seems that it already read values into string type and store by this command.  `std::string value = pRemoteCharacteristic->readValue();` 

How I can read hex or binary data from characteristics? Or I need to research for something more.

Thank you.

**Comment by chegewara** [comment]
Try to print read value length to see if there is any value. 
You can print bytes with `Serial.write` or use `ESP_LOG_BUFFER_HEX`.

**Comment by greatwuu** [comment]
I try to add other command to print byte but the result is still the same.
![image](https://user-images.githubusercontent.com/69145075/89251781-18c57200-d642-11ea-89fc-d2be9d35f237.png)

I add this to my sketch.
`if (pRemoteCharacteristic->canRead()) {
    std::string value = pRemoteCharacteristic->readValue();
    int j = value.length();
    Serial.print("Data length = ");
    Serial.println(j);
    Serial.print("The characteristic value was: ");
    //Serial.println(value.c_str());
    for (int i = 0; i < value.length(); i++)
    {
      Serial.write(value[i]);
    }
    Serial.println("");
  }`

And when I try to add `ESP_LOG_BUFFER_HEX("value", value, value.length());` it can't compile or maybe I use the wrong buffer pointer. If the problems is a pointer please give me some advice I still confuse with pointer

**Comment by greatwuu** [comment]
I see some discussion on [https://github.com/nkolban/esp32-snippets/issues/666](url)

but still didn't understand that notifyCallback function where does it get input from I did not see this function use any input.

this function declare with 
`static void notifyCallback(BLERemoteCharacteristic* pBLERemoteCharacteristic,uint8_t* pData,size_t length,bool isNotify)`

**Comment by chegewara** [comment]
here you can use that notation, because you are giving length:
`ESP_LOG_BUFFER_HEX("value", value.c_str(), value.length());`
so it does not matter if there is 0x0 in middle, or any non printable value, or you can do it that way:
`ESP_LOG_BUFFER_HEX("value", (uint8_t*)value.c_str(), value.length());`
It makes no difference here, because IIRC buffer is type of void*

**Comment by greatwuu** [comment]
> here you can use that notation, because you are giving length:
> `ESP_LOG_BUFFER_HEX("value", value.c_str(), value.length());`
> so it does not matter if there is 0x0 in middle, or any non printable value, or you can do it that way:
> `ESP_LOG_BUFFER_HEX("value", (uint8_t*)value.c_str(), value.length());`
> It makes no difference here, because IIRC buffer is type of void*

it can compile but still no data coming out did I need to pair or bond before reading Battery data because I've check the value.legth() result is = 0 so I have no idea. Anyway I use nRF Connect to emulate BLE service from my mobile phone.

**Comment by chegewara** [comment]
> Anyway I use nRF Connect to emulate BLE service from my mobile phone.

Did you set any value in nRF for that characteristic?

**Comment by greatwuu** [comment]
![image](https://user-images.githubusercontent.com/69145075/89261369-238b0180-d658-11ea-8282-e0059f8ce8d2.png)

Haha, I didn't see any setting did it should have. When hit the add service button the application only let me choose a service but have no rights to set value for it.

**Comment by chegewara** [comment]
For sure there is option to set value, at least on android it is.

**Comment by greatwuu** [comment]
Update I've added basic security to my sketch now I have output in string form 
![image](https://user-images.githubusercontent.com/69145075/89368077-da44bb80-d704-11ea-8c1b-bcc83d36a7e6.png)

Next step is to convert this value to hex.
